// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/data/repositories/inbox_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:almudeer_mobile_app/core/api/api_client.dart' as _i3;
import 'package:almudeer_mobile_app/core/services/connectivity_service.dart'
    as _i7;
import 'package:almudeer_mobile_app/core/services/persistent_cache_service.dart'
    as _i10;
import 'package:almudeer_mobile_app/data/datasources/local/inbox_local_datasource.dart'
    as _i9;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secureStorage(_i4.FlutterSecureStorage? storage) => super.noSuchMethod(
    Invocation.setter(#secureStorage, storage),
    returnValueForMissingStub: null,
  );

  @override
  void setTemporaryOverride(String? key) => super.noSuchMethod(
    Invocation.method(#setTemporaryOverride, [key]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String?> getLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseKey, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<int?> getLicenseId([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseId, [overrideKey]),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<void> setLicenseInfo({
    required String? key,
    int? id,
    String? accessToken,
    String? refreshToken,
    bool? updateActivePointer = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setLicenseInfo, [], {
              #key: key,
              #id: id,
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #updateActivePointer: updateActivePointer,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#clearLicenseKey, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> getAccountCacheHash() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountCacheHash, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAccountCacheHash, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String?> getAccessToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [overrideKey]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, [overrideKey]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Response> getRaw(
    String? url, {
    bool? requiresAuth = false,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRaw,
              [url],
              {
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #getRaw,
                  [url],
                  {
                    #requiresAuth: requiresAuth,
                    #overrideLicenseKey: overrideLicenseKey,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<Map<String, dynamic>> uploadMultipleFiles(
    String? endpoint, {
    required List<MapEntry<String, String>>? files,
    Map<String, String>? fields,
    String? method = 'POST',
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
    int? retryCount = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMultipleFiles,
              [endpoint],
              {
                #files: files,
                #fields: fields,
                #method: method,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
                #retryCount: retryCount,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadFile(
    String? endpoint, {
    required String? filePath,
    required String? fieldName,
    Map<String, String>? fields,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [endpoint],
              {
                #filePath: filePath,
                #fieldName: fieldName,
                #fields: fields,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  void scheduleProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#scheduleProactiveRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#cancelProactiveRefresh, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i7.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ConnectivityStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i7.ConnectivityStatus.online,
          )
          as _i7.ConnectivityStatus);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  bool get isServerReachable =>
      (super.noSuchMethod(
            Invocation.getter(#isServerReachable),
            returnValue: false,
          )
          as bool);

  @override
  Duration get currentPollInterval =>
      (super.noSuchMethod(
            Invocation.getter(#currentPollInterval),
            returnValue: _FakeDuration_1(
              this,
              Invocation.getter(#currentPollInterval),
            ),
          )
          as Duration);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addReconnectCallback(_i8.VoidCallback? callback) => super.noSuchMethod(
    Invocation.method(#addReconnectCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeReconnectCallback(_i8.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeReconnectCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i7.ConnectivityStatus> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i5.Future<_i7.ConnectivityStatus>.value(
              _i7.ConnectivityStatus.online,
            ),
          )
          as _i5.Future<_i7.ConnectivityStatus>);

  @override
  void clearReachabilityCache() => super.noSuchMethod(
    Invocation.method(#clearReachabilityCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [InboxLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxLocalDataSource extends _i1.Mock
    implements _i9.InboxLocalDataSource {
  MockInboxLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> cacheMessages(
    List<Map<String, dynamic>>? messages, {
    String? senderContact,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheMessages,
              [messages],
              {#senderContact: senderContact},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteMessageLocally(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessageLocally, [remoteId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> addMessageLocally({
    required String? senderContact,
    required String? body,
    String? channel = 'whatsapp',
    String? mediaUrl,
    int? replyToId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
    String? replyToSenderName,
    bool? isForwarded = false,
    List<Map<String, dynamic>>? attachments,
    String? receivedAt,
    String? urgency,
    String? sentiment,
    String? originalSender,
    String? deliveryStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMessageLocally, [], {
              #senderContact: senderContact,
              #body: body,
              #channel: channel,
              #mediaUrl: mediaUrl,
              #replyToId: replyToId,
              #replyToPlatformId: replyToPlatformId,
              #replyToBodyPreview: replyToBodyPreview,
              #replyToSenderName: replyToSenderName,
              #isForwarded: isForwarded,
              #attachments: attachments,
              #receivedAt: receivedAt,
              #urgency: urgency,
              #sentiment: sentiment,
              #originalSender: originalSender,
              #deliveryStatus: deliveryStatus,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getChatHistory(
    String? senderContact, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getChatHistory,
              [senderContact],
              {#limit: limit},
            ),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getMessageWithAttachments(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageWithAttachments, [localId]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getUnsyncedOutgoingMessages(
    String? senderContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedOutgoingMessages, [senderContact]),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> deleteOptimisticMessage(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOptimisticMessage, [localId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markAsSynced(
    int? localId,
    int? remoteId, {
    String? platformMessageId,
    String? channelMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markAsSynced,
              [localId, remoteId],
              {
                #platformMessageId: platformMessageId,
                #channelMessageId: channelMessageId,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> incrementRetryCount(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetryCount, [localId]),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<bool> hasExceededMaxRetries(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#hasExceededMaxRetries, [localId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getRetryableMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getRetryableMessages, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> updateMessageStatus(
    int? remoteId,
    String? status, {
    String? editedBody,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMessageStatus,
              [remoteId, status],
              {#editedBody: editedBody},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearChatHistory(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, [senderContact]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateMessageEditLocally(
    int? remoteId,
    String? newBody,
    String? editedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageEditLocally, [
              remoteId,
              newBody,
              editedAt,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateMessageSyncStatus(int? remoteId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageSyncStatus, [remoteId, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> persistRemoteMessage(Map<String, dynamic>? msg) =>
      (super.noSuchMethod(
            Invocation.method(#persistRemoteMessage, [msg]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<int> insertOutboxMessage({
    required String? channel,
    required String? body,
    String? recipientId,
    String? recipientContact,
    String? subject,
    int? inboxMessageId,
    int? replyToId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
    String? replyToSenderName,
    List<Map<String, dynamic>>? attachments,
    bool? isForwarded = false,
    String? status = 'pending',
    String? deliveryStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertOutboxMessage, [], {
              #channel: channel,
              #body: body,
              #recipientId: recipientId,
              #recipientContact: recipientContact,
              #subject: subject,
              #inboxMessageId: inboxMessageId,
              #replyToId: replyToId,
              #replyToPlatformId: replyToPlatformId,
              #replyToBodyPreview: replyToBodyPreview,
              #replyToSenderName: replyToSenderName,
              #attachments: attachments,
              #isForwarded: isForwarded,
              #status: status,
              #deliveryStatus: deliveryStatus,
            }),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getPendingOutboxMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOutboxMessages, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<void> markOutboxAsSynced(
    int? localId,
    int? remoteId, {
    String? platformMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markOutboxAsSynced,
              [localId, remoteId],
              {#platformMessageId: platformMessageId},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateOutboxStatus(
    int? remoteId,
    String? status, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateOutboxStatus,
              [remoteId, status],
              {#errorMessage: errorMessage},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteOutboxMessage(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOutboxMessage, [remoteId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheConversations(
    List<Map<String, dynamic>>? conversations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheConversations, [conversations]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<Map<String, dynamic>>> getConversations({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>?> getConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [senderContact]),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> updateConversationUnreadCount(
    String? senderContact,
    int? unreadCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationUnreadCount, [
              senderContact,
              unreadCount,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateConversationOnlineStatus(
    String? senderContact,
    bool? isOnline,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationOnlineStatus, [
              senderContact,
              isOnline,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> markConversationAsRead(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationAsRead, [senderContact]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [senderContact]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearConversations() =>
      (super.noSuchMethod(
            Invocation.method(#clearConversations, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> hasPendingOperation(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingOperation, [remoteId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> updateConversationContact(
    String? oldContact,
    String? newContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationContact, [
              oldContact,
              newContact,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateMessageSenderContact(
    String? oldContact,
    String? newContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageSenderContact, [
              oldContact,
              newContact,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [PersistentCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistentCacheService extends _i1.Mock
    implements _i10.PersistentCacheService {
  MockPersistentCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> put(
    String? boxName,
    String? key,
    dynamic data, {
    Duration? expiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [boxName, key, data], {#expiry: expiry}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<T?> get<T>(String? boxName, String? key, {Duration? expiry}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [boxName, key], {#expiry: expiry}),
            returnValue: _i5.Future<T?>.value(),
          )
          as _i5.Future<T?>);

  @override
  _i5.Future<void> delete(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [boxName, key]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearBox(String? boxName) =>
      (super.noSuchMethod(
            Invocation.method(#clearBox, [boxName]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteByPrefix(String? boxName, String? prefix) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByPrefix, [boxName, prefix]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
