// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/data/repositories/settings_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:almudeer_mobile_app/core/api/api_client.dart' as _i3;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secureStorage(_i4.FlutterSecureStorage? storage) => super.noSuchMethod(
    Invocation.setter(#secureStorage, storage),
    returnValueForMissingStub: null,
  );

  @override
  void setTemporaryOverride(String? key) => super.noSuchMethod(
    Invocation.method(#setTemporaryOverride, [key]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<String?> getLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseKey, []),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<int?> getLicenseId([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseId, [overrideKey]),
            returnValue: _i5.Future<int?>.value(),
          )
          as _i5.Future<int?>);

  @override
  _i5.Future<void> setLicenseInfo({
    required String? key,
    int? id,
    String? accessToken,
    String? refreshToken,
    bool? updateActivePointer = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setLicenseInfo, [], {
              #key: key,
              #id: id,
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #updateActivePointer: updateActivePointer,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#clearLicenseKey, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<String> getAccountCacheHash() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountCacheHash, []),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getAccountCacheHash, []),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<String?> getAccessToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [overrideKey]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<String?> getRefreshToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, [overrideKey]),
            returnValue: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.Response> getRaw(
    String? url, {
    bool? requiresAuth = false,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRaw,
              [url],
              {
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i5.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #getRaw,
                  [url],
                  {
                    #requiresAuth: requiresAuth,
                    #overrideLicenseKey: overrideLicenseKey,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response>);

  @override
  _i5.Future<Map<String, dynamic>> uploadMultipleFiles(
    String? endpoint, {
    required List<MapEntry<String, String>>? files,
    Map<String, String>? fields,
    String? method = 'POST',
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
    int? retryCount = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMultipleFiles,
              [endpoint],
              {
                #files: files,
                #fields: fields,
                #method: method,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
                #retryCount: retryCount,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<Map<String, dynamic>> uploadFile(
    String? endpoint, {
    required String? filePath,
    required String? fieldName,
    Map<String, String>? fields,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [endpoint],
              {
                #filePath: filePath,
                #fieldName: fieldName,
                #fields: fields,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  void scheduleProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#scheduleProactiveRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#cancelProactiveRefresh, []),
    returnValueForMissingStub: null,
  );
}
