"""
Al-Mudeer - Authentication Routes
JWT-based login, registration, and token management

SUPPORTS:
- Email/Password login (new flow)
- License key login (backward compatibility)
- Email signup with OTP verification
- Password reset via email
- Admin approval workflow

SECURITY FIXES:
- Content-Type validation on all auth endpoints
- Token validation before blacklisting on logout
- Constant-time response delays to prevent timing attacks
- Generic error messages to prevent username enumeration
- Rate limiting on /api/auth/me to prevent token enumeration
"""

import secrets
import re
from fastapi import APIRouter, HTTPException, status, Depends, Request
from pydantic import BaseModel, EmailStr
from typing import Optional

from services.jwt_auth import (
    create_token_pair,
    refresh_access_token,
    get_current_user,
)
from services.login_protection import (
    check_account_lockout,
    record_failed_login,
    record_successful_login,
    MAX_FAILED_ATTEMPTS,
)
from services.password_service import hash_password, verify_password, validate_password_strength
from services.otp_service import get_otp_service
from services.password_reset_service import get_password_reset_service
from logging_config import get_logger
from services.security_logger import get_security_logger, SecurityEventType
from services.token_blacklist import blacklist_token
from rate_limiting import limiter, RateLimits
from db_helper import get_db, fetch_one, execute_sql, commit_db

logger = get_logger(__name__)
router = APIRouter(prefix="/api/auth", tags=["Authentication"])


# ============ Security Helpers ============

async def _apply_constant_time_delay():
    """
    SECURITY FIX: Apply constant-time delay to prevent timing attacks.
    This ensures all auth responses take roughly the same time regardless of
    where in the validation flow they fail.
    """
    import asyncio
    # Random delay between 100-300ms to prevent timing analysis
    delay_ms = secrets.randbelow(200) + 100
    await asyncio.sleep(delay_ms / 1000.0)


def _validate_content_type(request: Request) -> bool:
    """
    SECURITY FIX: Validate Content-Type header to prevent CSRF attacks.
    CRITICAL FIX P1-11: Use strict MIME type matching to prevent bypass.
    """
    content_type = request.headers.get("content-type", "").strip().lower()
    # Strict validation: must be exactly application/json or application/json; charset=utf-8
    # Reject: text/plain, application/json-patch, etc.
    if content_type == "application/json":
        return True
    if content_type.startswith("application/json;"):
        # Allow charset parameter
        parts = content_type.split(";")
        if len(parts) == 2 and parts[0].strip() == "application/json":
            # Validate charset parameter format
            charset_part = parts[1].strip()
            if charset_part.startswith("charset="):
                charset = charset_part[8:].strip().lower()
                # Only allow utf-8 or utf-8 variants
                if charset in ("utf-8", "utf8"):
                    return True
    return False


# ============ Request/Response Models ============

class LoginRequest(BaseModel):
    """Login with email/password"""
    email: Optional[str] = None
    password: Optional[str] = None
    # Device fingerprint for token binding (generated by client, persisted in secure storage)
    device_fingerprint: Optional[str] = None


class SignUpRequest(BaseModel):
    """Sign up with email and password"""
    email: str
    password: str
    full_name: str
    username: str


class VerifyOTPRequest(BaseModel):
    """Verify email OTP code"""
    email: str
    otp_code: str


class ResendOTPRequest(BaseModel):
    """Resend OTP code"""
    email: str


class PasswordResetRequest(BaseModel):
    """Request password reset"""
    email: str


class PasswordResetConfirmRequest(BaseModel):
    """Confirm password reset with token"""
    token: str
    new_password: str


class ApprovalStatusResponse(BaseModel):
    """User approval status"""
    is_approved: bool
    approval_status: str  # 'pending', 'approved', 'rejected'
    is_email_verified: bool


class TokenResponse(BaseModel):
    """Token response"""
    access_token: str
    refresh_token: Optional[str] = None
    token_type: str = "bearer"
    expires_in: int
    user: Optional[dict] = None


class RefreshRequest(BaseModel):
    """Refresh token request"""
    refresh_token: str
    device_fingerprint: Optional[str] = None


# ============ Auth Endpoints ============

@router.post("/login", response_model=TokenResponse)
@limiter.limit(RateLimits.AUTH)  # P0 FIX: Rate limit login endpoint (5/minute)
async def login(data: LoginRequest, request: Request):
    """
    Login with email/password.

    Returns JWT tokens for authenticated access.

    SECURITY FIXES:
    - Content-Type validation
    - Constant-time response delay
    - Generic error messages
    - Admin approval check
    - Rate limiting (5/minute) to prevent brute-force attacks
    """
    # SECURITY FIX: Validate Content-Type
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    # Extract metadata
    ip_address = request.client.host if request.client else "unknown"

    if data.email and data.password:
        return await _login_with_email(
            data.email, data.password, ip_address, request,
            device_fingerprint=data.device_fingerprint,
        )
    else:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="يجب إدخال البريد الإلكتروني وكلمة المرور"
        )


async def _login_with_email(
    email_or_username: str, password: str, ip_address: str, request: Request,
    device_fingerprint: str = None,
):
    """
    Handle email/password or username/password login.

    Flow:
    1. Detect if input is email or username
    2. Check account exists (by email or username)
    3. Verify password
    4. Check email is verified
    5. Check admin approval
    6. Create JWT tokens
    """
    security_logger = get_security_logger()

    # Detect if input is email or username
    email_regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    is_email = bool(re.match(email_regex, email_or_username))
    
    # Build query and parameters based on input type
    if is_email:
        identifier = email_or_username.lower()
        query = """
            SELECT id, email, password_hash, full_name, username,
                   is_email_verified, is_approved_by_admin, approval_status
            FROM user_accounts
            WHERE email = ?
        """
        query_params = [identifier]
        brute_force_key = f"email:{identifier}"
    else:
        identifier = email_or_username.lower()
        query = """
            SELECT id, email, password_hash, full_name, username,
                   is_email_verified, is_approved_by_admin, approval_status
            FROM user_accounts
            WHERE username = ?
        """
        query_params = [identifier]
        brute_force_key = f"username:{identifier}"

    # Check brute-force protection
    is_locked, remaining = check_account_lockout(brute_force_key)
    is_ip_locked, ip_remaining = check_account_lockout(f"ip:{ip_address}")

    if is_locked or is_ip_locked:
        remaining_time = max(remaining or 0, ip_remaining or 0)
        await _apply_constant_time_delay()

        # P1 FIX: Log account lockout
        security_logger.log_account_locked(
            identifier=brute_force_key,
            ip_address=ip_address,
            attempts=MAX_FAILED_ATTEMPTS
        )

        detail_msg = "تم حظر الحساب مؤقتاً."
        if is_ip_locked and not is_locked:
            detail_msg = "تم حظر هذا الجهاز مؤقتاً بسبب كثرة المحاولات الفاشلة."
        
        raise HTTPException(
            status_code=status.HTTP_429_TOO_MANY_REQUESTS,
            detail=f"{detail_msg} حاول مرة أخرى بعد {remaining_time // 60} دقائق." if remaining_time > 60 else f"{detail_msg} حاول مرة أخرى بعد {remaining_time} ثانية.",
            headers={"Retry-After": str(remaining_time)},
        )

    async with get_db() as db:
        # Find user by email or username
        user = await fetch_one(db, query, query_params)

        if not user:
            # Record failed attempt
            record_failed_login(brute_force_key)
            record_failed_login(f"ip:{ip_address}")
            await _apply_constant_time_delay()

            # P1 FIX: Log failed login attempt
            security_logger.log_event(
                SecurityEventType.LOGIN_FAILED,
                identifier=brute_force_key,
                ip_address=ip_address,
                details={"reason": "user_not_found"},
                severity="WARNING"
            )

            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="البريد الإلكتروني/اسم المستخدم أو كلمة المرور غير صحيحة"
            )

        # Verify password
        if not verify_password(password, user["password_hash"]):
            record_failed_login(brute_force_key)
            record_failed_login(f"ip:{ip_address}")
            await _apply_constant_time_delay()

            # P1 FIX: Log failed login attempt
            security_logger.log_event(
                SecurityEventType.LOGIN_FAILED,
                identifier=brute_force_key,
                ip_address=ip_address,
                details={"reason": "invalid_password", "user_id": user["id"]},
                severity="WARNING"
            )

            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="البريد الإلكتروني/اسم المستخدم أو كلمة المرور غير صحيحة"
            )

        # P3-19 FIX: Rehash password if bcrypt rounds need upgrading
        from services.password_service import needs_rehash
        if needs_rehash(user["password_hash"]):
            new_hash = hash_password(password)
            await execute_sql(
                db,
                "UPDATE user_accounts SET password_hash = ?, updated_at = NOW() WHERE id = ?",
                [new_hash, user["id"]]
            )
            logger.info(f"Password hash upgraded for user {user['id']} (bcrypt rounds update)")

        # Check email is verified
        if not user.get("is_email_verified"):
            await _apply_constant_time_delay()
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={
                    "error": "يجب التحقق من البريد الإلكتروني أولاً",
                    "error_code": "EMAIL_NOT_VERIFIED",
                    "user_id": user["id"]
                }
            )

        # Check admin approval
        if not user.get("is_approved_by_admin"):
            await _apply_constant_time_delay()
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail={
                    "error": "حسابك قيد المراجعة. سيتم إعلامك عند الموافقة.",
                    "error_code": "PENDING_APPROVAL",
                    "approval_status": user.get("approval_status", "pending"),
                    "user_id": user["id"]
                }
            )

        # On success, clear failed attempts
        record_successful_login(brute_force_key)
        record_successful_login(f"ip:{ip_address}")

        # P1 FIX: Log successful login
        security_logger.log_event(
            SecurityEventType.LOGIN_SUCCESS,
            identifier=brute_force_key,
            ip_address=ip_address,
            details={"user_id": user["id"]}
        )

        # Update last login timestamp with IP tracking
        await execute_sql(
            db,
            "UPDATE user_accounts SET last_login = NOW(), last_login_ip = ?, updated_at = NOW() WHERE id = ?",
            [ip_address, user["id"]]
        )
        await commit_db(db)

    # Create JWT tokens
    request_ip = request.client.host if request.client else None
    tokens = await create_token_pair(
        user_id=str(user["id"]),
        role="user",
        ip_address=request_ip,
        user_agent=request.headers.get("User-Agent"),
        device_fingerprint=device_fingerprint,
    )

    # Build user info
    user_info = {
        "user_id": user["id"],
        "email": user["email"],
        "full_name": user.get("full_name"),
        "is_email_verified": True,
        "is_approved_by_admin": True,
    }

    return TokenResponse(
        **tokens,
        user=user_info
    )


# ============ Signup & OTP Endpoints ============

@router.post("/signup")
async def signup(data: SignUpRequest, request: Request):
    """
    Sign up with email and password.
    
    Flow:
    1. Validate email format
    2. Check email not already registered
    3. Validate password strength
    4. Hash password and create account
    5. Generate and send OTP
    6. Return success (user must verify OTP before login)
    """
    # Validate Content-Type
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    # Validate email format
    email_regex = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    if not re.match(email_regex, data.email):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="بريد إلكتروني غير صالح"
        )

    # Validate username format: alphanumeric, underscores, hyphens, 3-50 chars
    username_pattern = r'^[a-zA-Z0-9_-]{3,50}$'
    if not re.match(username_pattern, data.username):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="اسم المستخدم يجب أن يكون 3-50 حرفًا ويحتوي فقط على أحرف إنجليزية وأرقام وشرطات"
        )

    # Validate password strength
    is_valid, error_msg = validate_password_strength(data.password)
    if not is_valid:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg
        )

    async with get_db() as db:
        # Check if email already registered
        existing = await fetch_one(
            db,
            "SELECT id FROM user_accounts WHERE email = ?",
            [data.email.lower()]
        )
        if existing:
            await _apply_constant_time_delay()
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="البريد الإلكتروني مسجل بالفعل"
            )

        # Check if username already taken
        existing_username = await fetch_one(
            db,
            "SELECT id FROM user_accounts WHERE username = ?",
            [data.username.lower()]
        )
        if existing_username:
            await _apply_constant_time_delay()
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="اسم المستخدم مسجل بالفعل"
            )

        # Hash password
        password_hash = hash_password(data.password)

        # Create user account (pending approval, not verified)
        await execute_sql(
            db,
            """
            INSERT INTO user_accounts (email, password_hash, full_name, username, is_email_verified, is_approved_by_admin, approval_status)
            VALUES (?, ?, ?, ?, FALSE, FALSE, 'pending')
            """,
            [data.email.lower(), password_hash, data.full_name, data.username.lower()]
        )
        await commit_db(db)

    # Generate and send OTP
    otp_service = get_otp_service()
    success, error_msg = await otp_service.generate_and_send_otp(data.email)
    
    if not success:
        logger.error(f"Failed to send OTP after signup for {data.email}: {error_msg}")
        # Note: Account is created even if OTP email fails

    security_logger = get_security_logger()
    security_logger.log_security_event(
        SecurityEventType.USER_SIGNUP,
        user_id=data.email,
        details={"full_name": data.full_name, "username": data.username}
    )

    return {
        "success": True,
        "message": "تم إنشاء الحساب. يرجى التحقق من بريدك الإلكتروني لرمز التحقق.",
        "email": data.email
    }


@router.get("/check-username/{username}")
@limiter.limit(RateLimits.signup)
async def check_username(username: str, request: Request):
    """
    Check if a username is available.
    
    Returns availability status in real-time for signup forms.
    Validates format and checks uniqueness in database.
    """
    # Validate username format first
    username_pattern = r'^[a-zA-Z0-9_-]{3,50}$'
    if not re.match(username_pattern, username):
        return {
            "available": False,
            "valid_format": False,
            "message": "اسم المستخدم يجب أن يكون 3-50 حرفًا ويحتوي فقط على أحرف إنجليزية وأرقام وشرطات"
        }
    
    # Check if username is already taken
    async with get_db() as db:
        existing = await fetch_one(
            db,
            "SELECT id FROM user_accounts WHERE username = ?",
            [username.lower()]
        )
        
        if existing:
            return {
                "available": False,
                "valid_format": True,
                "message": "اسم المستخدم مسجل بالفعل"
            }
        
        return {
            "available": True,
            "valid_format": True,
            "message": "اسم المستخدم متاح"
        }


@router.post("/verify-otp")
async def verify_otp(data: VerifyOTPRequest, request: Request):
    """
    Verify email OTP code.
    
    On success, email is marked as verified.
    User can then login (pending admin approval).
    """
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    otp_service = get_otp_service()
    success, error_msg = await otp_service.verify_otp(data.email, data.otp_code)

    if not success:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg
        )

    return {
        "success": True,
        "message": "تم التحقق من البريد الإلكتروني بنجاح. حسابك قيد المراجعة من المسؤول."
    }


@router.post("/resend-otp")
async def resend_otp(data: ResendOTPRequest, request: Request):
    """
    Resend OTP code (with cooldown enforcement).
    """
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    otp_service = get_otp_service()
    success, error_msg = await otp_service.resend_otp(data.email)

    if not success:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg
        )

    return {
        "success": True,
        "message": f"تم إرسال رمز التحقق إلى {data.email}"
    }


# ============ Password Reset Endpoints ============

@router.post("/forgot-password")
async def forgot_password(data: PasswordResetRequest, request: Request):
    """
    Request password reset email.

    Always returns success (even if email doesn't exist) to prevent enumeration.
    """
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    reset_service = get_password_reset_service()
    success, error_msg = await reset_service.initiate_reset(data.email)

    if not success:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg
        )

    # P1 FIX: Log password reset request
    security_logger = get_security_logger()
    security_logger.log_event(
        SecurityEventType.PASSWORD_CHANGED,
        identifier=f"email:{data.email}",
        ip_address=request.client.host if request.client else None,
        details={"action": "reset_requested"},
        severity="INFO"
    )

    # Always return success to prevent email enumeration
    return {
        "success": True,
        "message": "إذا كان البريد الإلكتروني مسجلاً، ستتلقى رابط إعادة تعيين كلمة المرور."
    }


@router.post("/reset-password")
async def reset_password(data: PasswordResetConfirmRequest, request: Request):
    """
    Reset password using reset token from email.
    """
    if not _validate_content_type(request):
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Content-Type must be application/json"
        )

    reset_service = get_password_reset_service()
    success, error_msg = await reset_service.reset_password(data.token, data.new_password)

    if not success:
        await _apply_constant_time_delay()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=error_msg
        )

    # P1 FIX: Log successful password reset
    security_logger = get_security_logger()
    security_logger.log_event(
        SecurityEventType.PASSWORD_CHANGED,
        identifier="password_reset",
        ip_address=request.client.host if request.client else None,
        details={"action": "reset_completed"},
        severity="INFO"
    )

    return {
        "success": True,
        "message": "تم إعادة تعيين كلمة المرور بنجاح. يمكنك تسجيل الدخول الآن."
    }


# ============ Approval Status Endpoint ============

@router.get("/approval-status")
async def get_approval_status(request: Request):
    """
    Check if current user's account is approved by admin.
    
    Requires authenticated user (valid JWT).
    Used by mobile app to poll for approval status.
    """
    user = await get_current_user(request)
    
    async with get_db() as db:
        user_account = await fetch_one(
            db,
            """
            SELECT id, is_email_verified, is_approved_by_admin, approval_status, full_name, email
            FROM user_accounts
            WHERE id = ?
            """,
            [user.get("user_id")]
        )

        if not user_account:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="المستخدم غير موجود"
            )

        return {
            "success": True,
            "user_id": user_account["id"],
            "email": user_account.get("email"),
            "full_name": user_account.get("full_name"),
            "is_email_verified": user_account.get("is_email_verified", False),
            "is_approved_by_admin": user_account.get("is_approved_by_admin", False),
            "approval_status": user_account.get("approval_status", "pending")
        }


@router.post("/refresh", response_model=TokenResponse)
async def refresh_token(data: RefreshRequest, request: Request):
    """
    Refresh an expired access token.

    Use the refresh token to get a new access token.

    SECURITY FIX: Device fingerprint is validated to prevent token replay.
    """
    ip_address = request.client.host if request.client else None

    result = await refresh_access_token(
        data.refresh_token,
        ip_address,
        user_agent=request.headers.get("User-Agent"),
        device_fingerprint=data.device_fingerprint,
    )

    if not result:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired refresh token",
        )

    return TokenResponse(**result)


@router.get("/me")
@limiter.limit(RateLimits.USER_INFO)  # P2-13 FIX: Stricter rate limit (10/min) to prevent token enumeration
async def get_current_user_info(request: Request, user: dict = Depends(get_current_user)):
    """
    Get current user information.

    Returns comprehensive user data from the database without issuing new tokens.
    This is preferred over calling /login for user info as it doesn't rotate tokens.

    SECURITY FIX #4: Rate limited to prevent:
    - Token enumeration attacks
    - Server resource exhaustion
    - Bypass of login rate limits via stolen tokens

    P1-10 FIX: Sensitive fields (license_key) are no longer returned to prevent leakage.
    P1-10 FIX: Added audit logging for this endpoint.

    P2-13 FIX: Using stricter USER_INFO rate limit (10/min) instead of AUTH (5/min)
    to allow reasonable usage while still preventing abuse.
    """
    from db_helper import get_db, fetch_one

    # P1-10 FIX: Audit logging
    security_logger = get_security_logger()
    security_logger.log_event(
        SecurityEventType.SUSPICIOUS_ACTIVITY,
        identifier=f"user:{user.get('user_id')}",
        ip_address=request.client.host if request.client else None,
        details={"action": "user_info_requested", "license_id": user.get("license_id")},
        severity="INFO"
    )

    license_id = user.get("license_id")
    if not license_id:
        return {
            "success": True,
            "user": user,
        }

    async with get_db() as db:
        row = await fetch_one(db, "SELECT * FROM license_keys WHERE id = ?", [license_id])
        if not row:
            return {
                "success": True,
                "user": user,
            }

        row_dict = dict(row)

        # Build user info response (snake_case for mobile app compatibility)
        expires_at = row_dict.get("expires_at")
        if expires_at:
            if hasattr(expires_at, 'isoformat'):
                expires_at_str = expires_at.isoformat()
            else:
                expires_at_str = str(expires_at)
        else:
            expires_at_str = None

        # P1-10 FIX: Filter sensitive fields - license_key is NEVER returned
        # Mobile app should use the locally stored key instead
        return {
            "success": True,
            "user": {
                "license_id": row_dict.get("id"),
                "full_name": row_dict.get("full_name") or row_dict.get("company_name"),
                "profile_image_url": row_dict.get("profile_image_url"),
                "created_at": str(row_dict.get("created_at")) if row_dict.get("created_at") else None,
                "expires_at": expires_at_str,
                "is_trial": bool(row_dict.get("is_trial", False)),
                "referral_code": row_dict.get("referral_code"),
                "referral_count": row_dict.get("referral_count", 0),
                "username": row_dict.get("username"),
                # P1-10 FIX: license_key removed - was security risk
                "is_active": bool(row_dict.get("is_active", True)),
            }
        }


class LogoutRequest(BaseModel):
    """Logout request model"""
    revoke_all_sessions: bool = False


@router.post("/logout")
async def logout(
    request: Request,
    data: LogoutRequest = None,
    user: dict = Depends(get_current_user)
):
    """
    Logout and invalidate the current token.

    Args:
        revoke_all_sessions: If True, revoke ALL sessions for this user (logout from all devices)
    
    SECURITY FIX: Token is now validated before blacklisting to prevent:
    - JTI guessing attacks
    - DoS via blacklist flooding
    - Blacklisting arbitrary/malformed tokens
    """
    data = data or LogoutRequest()

    # Get the token from the Authorization header
    auth_header = request.headers.get("Authorization", "")
    if not auth_header.startswith("Bearer "):
        # No valid token in header, but still return success for idempotency
        return {"success": True, "message": "Logged out successfully"}
    
    token = auth_header[7:]

    # SECURITY FIX: Validate token signature and expiry BEFORE blacklisting
    # This prevents attackers from blacklisting arbitrary JTIs
    try:
        from jose import jwt, JWTError
        from services.jwt_auth import config
        from services.token_blacklist import is_token_blacklisted
        from datetime import datetime, timezone
        
        # First check if already blacklisted (idempotency)
        try:
            # OFFLINE-FIRST: Disable expiration check on logout too
            payload = jwt.decode(token, config.secret_key, algorithms=[config.algorithm], options={"verify_exp": False})
            jti = payload.get("jti")

            if jti and is_token_blacklisted(jti):
                logger.debug(f"Token {jti[:8]}... already blacklisted, skipping")
                return {"success": True, "message": "Logged out successfully"}
        except JWTError:
            # Token is invalid, but still return success for idempotency
            logger.debug("Logout with invalid token - returning success for idempotency")
            return {"success": True, "message": "Logged out successfully"}

        # Token is valid, proceed with logout
        family_id = payload.get("family_id")

        if jti:
            # OFFLINE-FIRST: Use far-future expiry for blacklist (tokens don't expire)
            expires_at = datetime.now(timezone.utc) + timedelta(days=365*10)  # 10 years

            from database import DB_TYPE
            from db_helper import get_db, execute_sql, commit_db

            async with get_db() as db:
                # Revoke all sessions if requested (admin action)
                if data.revoke_all_sessions and user.get("license_id"):
                    if DB_TYPE == "postgresql":
                        await execute_sql(db, "UPDATE device_sessions SET is_revoked = TRUE WHERE license_key_id = ?", [user.get("license_id")])
                    else:
                        await execute_sql(db, "UPDATE device_sessions SET is_revoked = 1 WHERE license_key_id = ?", [user.get("license_id")])
                    await commit_db(db)
                    logger.info(f"All sessions revoked for user: {user.get('user_id')}")
                elif family_id:
                    # Revoke only current session (user-initiated logout)
                    if DB_TYPE == "postgresql":
                        await execute_sql(db, "UPDATE device_sessions SET is_revoked = TRUE WHERE family_id = ?", [family_id])
                    else:
                        await execute_sql(db, "UPDATE device_sessions SET is_revoked = 1 WHERE family_id = ?", [family_id])
                    await commit_db(db)
                    logger.info(f"Device session revoked for family: {family_id}")

            # Blacklist the token
            blacklist_token(jti, expires_at)

            security_logger = get_security_logger()
            security_logger.log_logout(user.get('user_id'))
            security_logger.log_token_blacklisted(user.get('user_id'), jti)

            logger.info(f"User logged out and token blacklisted: {user.get('user_id')}")

    except Exception as e:
        # SECURITY FIX #13: Log detailed error for debugging
        logger.error(f"Logout DB error: {type(e).__name__}: {e}")
        # SECURITY FIX #13: Return 503 error to inform user logout may not have completed
        # This prevents silent failures where user thinks they logged out but session remains active
        # CRITICAL FIX: Include specific error code so mobile can handle appropriately
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail={
                "error": "تعذر تسجيل الخروج بشكل كامل. يرجى المحاولة مرة أخرى.",
                "error_code": "LOGOUT_INCOMPLETE",
                "session_may_be_active": True,
            },
            headers={"Retry-After": "5"},
        )

    return {"success": True, "message": "Logged out successfully"}


# ============ Session Management ============

# Removed: Public session management endpoints.
# Internal session tracking (device_sessions) is preserved for JWT security (RTR).
