// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/providers/athkar_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:almudeer_mobile_app/core/services/offline_sync_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OfflineSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineSyncService extends _i1.Mock
    implements _i2.OfflineSyncService {
  MockOfflineSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SyncStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i2.SyncStatus.idle,
          )
          as _i2.SyncStatus);

  @override
  int get syncedCount =>
      (super.noSuchMethod(Invocation.getter(#syncedCount), returnValue: 0)
          as int);

  @override
  int get totalCount =>
      (super.noSuchMethod(Invocation.getter(#totalCount), returnValue: 0)
          as int);

  @override
  bool get isSyncing =>
      (super.noSuchMethod(Invocation.getter(#isSyncing), returnValue: false)
          as bool);

  @override
  int get pendingCount =>
      (super.noSuchMethod(Invocation.getter(#pendingCount), returnValue: 0)
          as int);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncAll() =>
      (super.noSuchMethod(
            Invocation.method(#syncAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> syncPendingOperations() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingOperations, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> forceSync() =>
      (super.noSuchMethod(
            Invocation.method(#forceSync, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueQuranProgress(int? surah, int? verse) =>
      (super.noSuchMethod(
            Invocation.method(#queueQuranProgress, [surah, verse]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getQuranProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getQuranProgress, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<Map<String, dynamic>?> getAthkarProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getAthkarProgress, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<void> queueAthkarProgress(
    Map<String, int>? counts,
    int? misbaha,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#queueAthkarProgress, [counts, misbaha]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueSendMessage(
    String? senderContact,
    String? body, {
    String? mediaPath,
    String? channel = 'whatsapp',
    int? replyToMessageId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queueSendMessage,
              [senderContact, body],
              {
                #mediaPath: mediaPath,
                #channel: channel,
                #replyToMessageId: replyToMessageId,
                #replyToPlatformId: replyToPlatformId,
                #replyToBodyPreview: replyToBodyPreview,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueDelete(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#queueDelete, [messageId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueDeleteConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#queueDeleteConversation, [senderContact]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueAddCustomer(Map<String, dynamic>? customerData) =>
      (super.noSuchMethod(
            Invocation.method(#queueAddCustomer, [customerData]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueUpdateCustomer(
    int? remoteId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#queueUpdateCustomer, [remoteId, updates]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueDeleteCustomer(int? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#queueDeleteCustomer, [customerId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> queueAddLibraryNote({
    required String? title,
    required String? content,
    int? customerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queueAddLibraryNote, [], {
              #title: title,
              #content: content,
              #customerId: customerId,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
