// Mock file for AthkarProvider tests
// Generated by build_runner - DO NOT EDIT MANUALLY
// Run: flutter pub run build_runner build --delete-conflicting-outputs

import 'package:mockito/mockito.dart';
import 'package:almudeer_mobile_app/core/services/offline_sync_service.dart';

class MockOfflineSyncService extends Mock implements OfflineSyncService {}
