// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/presentation/widgets/chat/message_edit_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:almudeer_mobile_app/core/api/api_client.dart' as _i2;
import 'package:almudeer_mobile_app/core/services/connectivity_service.dart'
    as _i13;
import 'package:almudeer_mobile_app/core/services/message_cache_service.dart'
    as _i15;
import 'package:almudeer_mobile_app/core/services/websocket_service.dart'
    as _i14;
import 'package:almudeer_mobile_app/data/datasources/local/inbox_local_datasource.dart'
    as _i16;
import 'package:almudeer_mobile_app/data/models/conversation.dart' as _i3;
import 'package:almudeer_mobile_app/data/models/inbox_message.dart' as _i4;
import 'package:almudeer_mobile_app/data/repositories/inbox_repository.dart'
    as _i5;
import 'package:almudeer_mobile_app/presentation/providers/conversation_detail_provider.dart'
    as _i11;
import 'package:almudeer_mobile_app/presentation/providers/inbox_provider.dart'
    as _i8;
import 'package:flutter/foundation.dart' as _i12;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i17;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationsResponse_1 extends _i1.SmartFake
    implements _i3.ConversationsResponse {
  _FakeConversationsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConversationDetailResponse_2 extends _i1.SmartFake
    implements _i4.ConversationDetailResponse {
  _FakeConversationDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInboxMessagesResponse_3 extends _i1.SmartFake
    implements _i4.InboxMessagesResponse {
  _FakeInboxMessagesResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInboxMessage_4 extends _i1.SmartFake implements _i4.InboxMessage {
  _FakeInboxMessage_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCursorPaginatedMessages_5 extends _i1.SmartFake
    implements _i5.CursorPaginatedMessages {
  _FakeCursorPaginatedMessages_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_6 extends _i1.SmartFake implements Duration {
  _FakeDuration_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_7 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxRepository extends _i1.Mock implements _i5.InboxRepository {
  MockInboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i7.Future<_i3.ConversationsResponse> getConversations({
    int? limit = 25,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<_i3.ConversationsResponse>.value(
              _FakeConversationsResponse_1(
                this,
                Invocation.method(#getConversations, [], {
                  #limit: limit,
                  #offset: offset,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.ConversationsResponse>);

  @override
  _i7.Future<void> deleteConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> archiveConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#archiveConversation, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> togglePinConversation(
    String? senderContact,
    bool? isPinned,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#togglePinConversation, [
              senderContact,
              isPinned,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearConversationMessages(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#clearConversationMessages, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, int>?> getUnreadCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCounts, []),
            returnValue: _i7.Future<Map<String, int>?>.value(),
          )
          as _i7.Future<Map<String, int>?>);

  @override
  _i7.Future<_i4.ConversationDetailResponse> getConversationDetail(
    String? senderContact, {
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getConversationDetail,
              [senderContact],
              {#limit: limit},
            ),
            returnValue: _i7.Future<_i4.ConversationDetailResponse>.value(
              _FakeConversationDetailResponse_2(
                this,
                Invocation.method(
                  #getConversationDetail,
                  [senderContact],
                  {#limit: limit},
                ),
              ),
            ),
          )
          as _i7.Future<_i4.ConversationDetailResponse>);

  @override
  _i7.Future<_i4.InboxMessagesResponse> getInboxMessages({
    String? status,
    String? channel,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInboxMessages, [], {
              #status: status,
              #channel: channel,
              #limit: limit,
            }),
            returnValue: _i7.Future<_i4.InboxMessagesResponse>.value(
              _FakeInboxMessagesResponse_3(
                this,
                Invocation.method(#getInboxMessages, [], {
                  #status: status,
                  #channel: channel,
                  #limit: limit,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.InboxMessagesResponse>);

  @override
  _i7.Future<_i4.InboxMessage> getInboxMessage(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getInboxMessage, [id]),
            returnValue: _i7.Future<_i4.InboxMessage>.value(
              _FakeInboxMessage_4(
                this,
                Invocation.method(#getInboxMessage, [id]),
              ),
            ),
          )
          as _i7.Future<_i4.InboxMessage>);

  @override
  _i7.Future<void> markMessageRead(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageRead, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markConversationRead(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationRead, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWhatsAppTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#getWhatsAppTemplates, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>> sendMessage(
    String? senderContact, {
    required String? message,
    String? channel,
    List<Map<String, dynamic>>? attachments,
    int? replyToMessageId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
    String? replyToSenderName,
    bool? isForwarded = false,
    void Function(double)? onUploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendMessage,
              [senderContact],
              {
                #message: message,
                #channel: channel,
                #attachments: attachments,
                #replyToMessageId: replyToMessageId,
                #replyToPlatformId: replyToPlatformId,
                #replyToBodyPreview: replyToBodyPreview,
                #replyToSenderName: replyToSenderName,
                #isForwarded: isForwarded,
                #onUploadProgress: onUploadProgress,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i5.CursorPaginatedMessages> getConversationMessagesCursor(
    String? senderContact, {
    String? cursor,
    int? limit = 25,
    String? direction = 'older',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getConversationMessagesCursor,
              [senderContact],
              {#cursor: cursor, #limit: limit, #direction: direction},
            ),
            returnValue: _i7.Future<_i5.CursorPaginatedMessages>.value(
              _FakeCursorPaginatedMessages_5(
                this,
                Invocation.method(
                  #getConversationMessagesCursor,
                  [senderContact],
                  {#cursor: cursor, #limit: limit, #direction: direction},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.CursorPaginatedMessages>);

  @override
  _i7.Future<List<_i4.InboxMessage>> getUnsyncedOutgoingMessages(
    String? senderContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedOutgoingMessages, [senderContact]),
            returnValue: _i7.Future<List<_i4.InboxMessage>>.value(
              <_i4.InboxMessage>[],
            ),
          )
          as _i7.Future<List<_i4.InboxMessage>>);

  @override
  _i7.Future<Map<String, dynamic>> editMessage(
    int? messageId,
    String? newBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [messageId, newBody]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> applyRemoteMessageEdit(
    int? messageId,
    String? newBody,
    String? editedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteMessageEdit, [
              messageId,
              newBody,
              editedAt,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> applyRemoteMessageDelete(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteMessageDelete, [messageId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> deleteMessage(
    int? messageId, {
    bool? isOutgoing = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteMessage,
              [messageId],
              {#isOutgoing: isOutgoing},
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> restoreMessage(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreMessage, [messageId]),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<List<_i4.InboxMessage>> searchMessages(
    String? query, {
    String? senderContact,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchMessages,
              [query],
              {#senderContact: senderContact, #limit: limit, #offset: offset},
            ),
            returnValue: _i7.Future<List<_i4.InboxMessage>>.value(
              <_i4.InboxMessage>[],
            ),
          )
          as _i7.Future<List<_i4.InboxMessage>>);

  @override
  _i7.Future<void> setTypingStatus(String? senderContact, bool? isTyping) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [senderContact, isTyping]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setRecordingStatus(
    String? senderContact,
    bool? isRecording,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setRecordingStatus, [
              senderContact,
              isRecording,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String?> getDraft(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#getDraft, [senderContact]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> saveDraft(String? senderContact, String? text) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [senderContact, text]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateMessageSyncStatus(int? remoteId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageSyncStatus, [remoteId, status]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> persistRemoteMessage(Map<String, dynamic>? message) =>
      (super.noSuchMethod(
            Invocation.method(#persistRemoteMessage, [message]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> hasConflictingPendingOperation(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#hasConflictingPendingOperation, [messageId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> applyRemoteMessageEditIfNoConflict(
    int? messageId,
    String? newBody,
    String? editedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteMessageEditIfNoConflict, [
              messageId,
              newBody,
              editedAt,
            ]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> applyRemoteDeleteIfNoConflict(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#applyRemoteDeleteIfNoConflict, [messageId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> migrateConversationContact(
    String? oldContact,
    String? newContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#migrateConversationContact, [
              oldContact,
              newContact,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [InboxProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxProvider extends _i1.Mock implements _i8.InboxProvider {
  MockInboxProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.InboxState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i8.InboxState.initial,
          )
          as _i8.InboxState);

  @override
  List<_i3.Conversation> get conversations =>
      (super.noSuchMethod(
            Invocation.getter(#conversations),
            returnValue: <_i3.Conversation>[],
          )
          as List<_i3.Conversation>);

  @override
  int get total =>
      (super.noSuchMethod(Invocation.getter(#total), returnValue: 0) as int);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<String> get recentSearches =>
      (super.noSuchMethod(
            Invocation.getter(#recentSearches),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  int get unreadCount =>
      (super.noSuchMethod(Invocation.getter(#unreadCount), returnValue: 0)
          as int);

  @override
  int get totalUnreadCount =>
      (super.noSuchMethod(Invocation.getter(#totalUnreadCount), returnValue: 0)
          as int);

  @override
  String get sortBy =>
      (super.noSuchMethod(
            Invocation.getter(#sortBy),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#sortBy),
            ),
          )
          as String);

  @override
  bool get sortDescending =>
      (super.noSuchMethod(
            Invocation.getter(#sortDescending),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.Conversation> get filteredConversations =>
      (super.noSuchMethod(
            Invocation.getter(#filteredConversations),
            returnValue: <_i3.Conversation>[],
          )
          as List<_i3.Conversation>);

  @override
  List<_i3.Conversation> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i3.Conversation>[],
          )
          as List<_i3.Conversation>);

  @override
  bool get isSelectionMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSelectionMode),
            returnValue: false,
          )
          as bool);

  @override
  Set<int> get selectedIds =>
      (super.noSuchMethod(Invocation.getter(#selectedIds), returnValue: <int>{})
          as Set<int>);

  @override
  int get selectedCount =>
      (super.noSuchMethod(Invocation.getter(#selectedCount), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isTyping(String? contact) =>
      (super.noSuchMethod(
            Invocation.method(#isTyping, [contact]),
            returnValue: false,
          )
          as bool);

  @override
  void setTypingStatus(String? contact, bool? isTyping) => super.noSuchMethod(
    Invocation.method(#setTypingStatus, [contact, isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void clearTypingStatus(String? contact) => super.noSuchMethod(
    Invocation.method(#clearTypingStatus, [contact]),
    returnValueForMissingStub: null,
  );

  @override
  void setSortBy(String? sortBy, {bool? descending}) => super.noSuchMethod(
    Invocation.method(#setSortBy, [sortBy], {#descending: descending}),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadConversations({
    bool? refresh = false,
    bool? forceRefresh = false,
    bool? skipAutoRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadConversations, [], {
              #refresh: refresh,
              #forceRefresh: forceRefresh,
              #skipAutoRefresh: skipAutoRefresh,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loadMoreConversations() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreConversations, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> refresh() =>
      (super.noSuchMethod(
            Invocation.method(#refresh, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> refreshUnreadCounts() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUnreadCounts, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void onAppResume() => super.noSuchMethod(
    Invocation.method(#onAppResume, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i4.InboxMessage>> searchMessages(
    String? query, {
    String? senderContact,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchMessages,
              [query],
              {#senderContact: senderContact},
            ),
            returnValue: _i7.Future<List<_i4.InboxMessage>>.value(
              <_i4.InboxMessage>[],
            ),
          )
          as _i7.Future<List<_i4.InboxMessage>>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadRecentSearches() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentSearches, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> saveSearchQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#saveSearchQuery, [query]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearRecentSearches() =>
      (super.noSuchMethod(
            Invocation.method(#clearRecentSearches, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteIndividualSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIndividualSearch, [query]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  List<_i3.Conversation> getFrequentContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getFrequentContacts, []),
            returnValue: <_i3.Conversation>[],
          )
          as List<_i3.Conversation>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isSelected(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isSelected, [id]),
            returnValue: false,
          )
          as bool);

  @override
  void toggleSelectionMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleSelectionMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSelection(int? id) => super.noSuchMethod(
    Invocation.method(#toggleSelection, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void selectAll() => super.noSuchMethod(
    Invocation.method(#selectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> bulkDelete() =>
      (super.noSuchMethod(
            Invocation.method(#bulkDelete, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteConversation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void restoreConversation(_i3.Conversation? conversation) =>
      super.noSuchMethod(
        Invocation.method(#restoreConversation, [conversation]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> archiveConversation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#archiveConversation, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> togglePinConversation(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#togglePinConversation, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAllAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllAsRead, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkArchive() =>
      (super.noSuchMethod(
            Invocation.method(#bulkArchive, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkMarkAsRead() =>
      (super.noSuchMethod(
            Invocation.method(#bulkMarkAsRead, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAsRead(int? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [conversationId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void markAsUnread(int? conversationId) => super.noSuchMethod(
    Invocation.method(#markAsUnread, [conversationId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateLastMessage({
    required int? conversationId,
    required String? body,
    required String? status,
    required DateTime? createdAt,
  }) => super.noSuchMethod(
    Invocation.method(#updateLastMessage, [], {
      #conversationId: conversationId,
      #body: body,
      #status: status,
      #createdAt: createdAt,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageEdit({
    required String? senderContact,
    required String? body,
  }) => super.noSuchMethod(
    Invocation.method(#updateMessageEdit, [], {
      #senderContact: senderContact,
      #body: body,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void updateConversation(_i3.Conversation? updated) => super.noSuchMethod(
    Invocation.method(#updateConversation, [updated]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationDetailProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationDetailProvider extends _i1.Mock
    implements _i11.ConversationDetailProvider {
  MockConversationDetailProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.ConversationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i11.ConversationState.initial,
          )
          as _i11.ConversationState);

  @override
  List<_i4.InboxMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i4.InboxMessage>[],
          )
          as List<_i4.InboxMessage>);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get isPeerTyping =>
      (super.noSuchMethod(Invocation.getter(#isPeerTyping), returnValue: false)
          as bool);

  @override
  bool get isPeerRecording =>
      (super.noSuchMethod(
            Invocation.getter(#isPeerRecording),
            returnValue: false,
          )
          as bool);

  @override
  bool get isPeerOnline =>
      (super.noSuchMethod(Invocation.getter(#isPeerOnline), returnValue: false)
          as bool);

  @override
  bool get isLocalUserOnline =>
      (super.noSuchMethod(
            Invocation.getter(#isLocalUserOnline),
            returnValue: false,
          )
          as bool);

  @override
  bool get isEditing =>
      (super.noSuchMethod(Invocation.getter(#isEditing), returnValue: false)
          as bool);

  @override
  bool get isSearching =>
      (super.noSuchMethod(Invocation.getter(#isSearching), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<int> get searchResultIds =>
      (super.noSuchMethod(
            Invocation.getter(#searchResultIds),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  int get currentSearchIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentSearchIndex),
            returnValue: 0,
          )
          as int);

  @override
  int get totalSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#totalSearchResults),
            returnValue: 0,
          )
          as int);

  @override
  bool get isSelectionMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSelectionMode),
            returnValue: false,
          )
          as bool);

  @override
  Set<int> get selectedMessageIds =>
      (super.noSuchMethod(
            Invocation.getter(#selectedMessageIds),
            returnValue: <int>{},
          )
          as Set<int>);

  @override
  int get selectedCount =>
      (super.noSuchMethod(Invocation.getter(#selectedCount), returnValue: 0)
          as int);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  List<Map<String, dynamic>> get whatsappTemplates =>
      (super.noSuchMethod(
            Invocation.getter(#whatsappTemplates),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  set onError(_i12.ValueChanged<String>? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isMessageSelected(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isMessageSelected, [id]),
            returnValue: false,
          )
          as bool);

  @override
  String getDraft(String? contact) =>
      (super.noSuchMethod(
            Invocation.method(#getDraft, [contact]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getDraft, [contact]),
            ),
          )
          as String);

  @override
  _i7.Future<void> loadConversation(
    String? senderContact, {
    String? senderName,
    String? channel,
    String? lastSeenAt,
    bool? isOnline = false,
    bool? fresh = true,
    bool? skipAutoRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadConversation,
              [senderContact],
              {
                #senderName: senderName,
                #channel: channel,
                #lastSeenAt: lastSeenAt,
                #isOnline: isOnline,
                #fresh: fresh,
                #skipAutoRefresh: skipAutoRefresh,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loadMoreMessages() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreMessages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addOptimisticMessage(_i4.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#addOptimisticMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void setReplyMessage(_i4.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#setReplyMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelReply() => super.noSuchMethod(
    Invocation.method(#cancelReply, []),
    returnValueForMissingStub: null,
  );

  @override
  void markMessageFailed(int? tempId) => super.noSuchMethod(
    Invocation.method(#markMessageFailed, [tempId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageUploadProgress(
    int? messageId,
    double? progress,
    int? uploadedBytes,
    int? totalBytes,
  ) => super.noSuchMethod(
    Invocation.method(#updateMessageUploadProgress, [
      messageId,
      progress,
      uploadedBytes,
      totalBytes,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageAttachments(
    int? messageId,
    List<Map<String, dynamic>>? attachments,
  ) => super.noSuchMethod(
    Invocation.method(#updateMessageAttachments, [messageId, attachments]),
    returnValueForMissingStub: null,
  );

  @override
  void confirmMessageSent(
    int? tempId,
    int? realId,
    String? status, {
    int? outboxId,
  }) => super.noSuchMethod(
    Invocation.method(
      #confirmMessageSent,
      [tempId, realId, status],
      {#outboxId: outboxId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> editMessage(int? messageId, String? newBody) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [messageId, newBody]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> deleteMessage(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> clearActiveChatMessages() =>
      (super.noSuchMethod(
            Invocation.method(#clearActiveChatMessages, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> saveDraft(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [text]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearDraft(String? contact) => super.noSuchMethod(
    Invocation.method(#clearDraft, [contact]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> fetchWhatsAppTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWhatsAppTemplates, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void toggleSelectionMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleSelectionMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMessageSelection(int? id) => super.noSuchMethod(
    Invocation.method(#toggleMessageSelection, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void selectAll() => super.noSuchMethod(
    Invocation.method(#selectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void exitSelectionMode() => super.noSuchMethod(
    Invocation.method(#exitSelectionMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectAllMessages() => super.noSuchMethod(
    Invocation.method(#selectAllMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.InboxMessage> getSelectedMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedMessages, []),
            returnValue: <_i4.InboxMessage>[],
          )
          as List<_i4.InboxMessage>);

  @override
  void copySelectedMessages() => super.noSuchMethod(
    Invocation.method(#copySelectedMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> forwardSelectedMessages() =>
      (super.noSuchMethod(
            Invocation.method(#forwardSelectedMessages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> bulkDeleteMessages() =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteMessages, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool undoLastBulkDelete() =>
      (super.noSuchMethod(
            Invocation.method(#undoLastBulkDelete, []),
            returnValue: false,
          )
          as bool);

  @override
  void clearUndoStack() => super.noSuchMethod(
    Invocation.method(#clearUndoStack, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> shareMessages(
    List<int>? messageIds,
    _i3.Conversation? targetConversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shareMessages, [messageIds, targetConversation]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void startEditingMessage(_i4.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#startEditingMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelEditing() => super.noSuchMethod(
    Invocation.method(#cancelEditing, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<bool> saveEditedMessage(
    String? newBody,
    _i8.InboxProvider? inboxProvider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditedMessage, [newBody, inboxProvider]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllCache() => super.noSuchMethod(
    Invocation.method(#clearAllCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void setTypingStatus(bool? isTyping) => super.noSuchMethod(
    Invocation.method(#setTypingStatus, [isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void setRecordingStatus(bool? isRecording) => super.noSuchMethod(
    Invocation.method(#setRecordingStatus, [isRecording]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void startSearching() => super.noSuchMethod(
    Invocation.method(#startSearching, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSearching() => super.noSuchMethod(
    Invocation.method(#stopSearching, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> updateSearchQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#updateSearchQuery, [query]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void nextSearchResult() => super.noSuchMethod(
    Invocation.method(#nextSearchResult, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousSearchResult() => super.noSuchMethod(
    Invocation.method(#previousSearchResult, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i13.ConnectivityService {
  MockConnectivityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.ConnectivityStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i13.ConnectivityStatus.online,
          )
          as _i13.ConnectivityStatus);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  bool get isServerReachable =>
      (super.noSuchMethod(
            Invocation.getter(#isServerReachable),
            returnValue: false,
          )
          as bool);

  @override
  Duration get currentPollInterval =>
      (super.noSuchMethod(
            Invocation.getter(#currentPollInterval),
            returnValue: _FakeDuration_6(
              this,
              Invocation.getter(#currentPollInterval),
            ),
          )
          as Duration);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addReconnectCallback(_i10.VoidCallback? callback) => super.noSuchMethod(
    Invocation.method(#addReconnectCallback, [callback]),
    returnValueForMissingStub: null,
  );

  @override
  void removeReconnectCallback(_i10.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#removeReconnectCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i13.ConnectivityStatus> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i7.Future<_i13.ConnectivityStatus>.value(
              _i13.ConnectivityStatus.online,
            ),
          )
          as _i7.Future<_i13.ConnectivityStatus>);

  @override
  void clearReachabilityCache() => super.noSuchMethod(
    Invocation.method(#clearReachabilityCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WebSocketService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWebSocketService extends _i1.Mock implements _i14.WebSocketService {
  MockWebSocketService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<Map<String, dynamic>> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<Map<String, dynamic>>.empty(),
          )
          as _i7.Stream<Map<String, dynamic>>);

  @override
  _i7.Stream<_i14.WebSocketState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i7.Stream<_i14.WebSocketState>.empty(),
          )
          as _i7.Stream<_i14.WebSocketState>);

  @override
  _i14.WebSocketState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i14.WebSocketState.disconnected,
          )
          as _i14.WebSocketState);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i7.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void send(Map<String, dynamic>? data) => super.noSuchMethod(
    Invocation.method(#send, [data]),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void forceReconnect() => super.noSuchMethod(
    Invocation.method(#forceReconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [MessageCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageCacheService extends _i1.Mock
    implements _i15.MessageCacheService {
  MockMessageCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheMessages(
    String? senderContact,
    List<_i4.InboxMessage>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheMessages, [senderContact, messages]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.InboxMessage>?> getCachedMessages(
    String? senderContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMessages, [senderContact]),
            returnValue: _i7.Future<List<_i4.InboxMessage>?>.value(),
          )
          as _i7.Future<List<_i4.InboxMessage>?>);

  @override
  List<_i4.InboxMessage> mergeMessages(
    List<_i4.InboxMessage>? cached,
    List<_i4.InboxMessage>? fresh,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mergeMessages, [cached, fresh]),
            returnValue: <_i4.InboxMessage>[],
          )
          as List<_i4.InboxMessage>);

  @override
  _i7.Future<void> clearConversationCache(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#clearConversationCache, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheConversations(List<_i3.Conversation>? conversations) =>
      (super.noSuchMethod(
            Invocation.method(#cacheConversations, [conversations]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Conversation>?> getCachedConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedConversations, []),
            returnValue: _i7.Future<List<_i3.Conversation>?>.value(),
          )
          as _i7.Future<List<_i3.Conversation>?>);

  @override
  _i7.Future<void> cacheConversationsByFilter(
    String? filterKey,
    List<_i3.Conversation>? conversations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheConversationsByFilter, [
              filterKey,
              conversations,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.Conversation>?> getCachedConversationsByFilter(
    String? filterKey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedConversationsByFilter, [filterKey]),
            returnValue: _i7.Future<List<_i3.Conversation>?>.value(),
          )
          as _i7.Future<List<_i3.Conversation>?>);

  @override
  _i7.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, int>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i7.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i7.Future<Map<String, int>>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [InboxLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockInboxLocalDataSource extends _i1.Mock
    implements _i16.InboxLocalDataSource {
  MockInboxLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> cacheMessages(
    List<Map<String, dynamic>>? messages, {
    String? senderContact,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheMessages,
              [messages],
              {#senderContact: senderContact},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteMessageLocally(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessageLocally, [remoteId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> addMessageLocally({
    required String? senderContact,
    required String? body,
    String? channel = 'whatsapp',
    String? mediaUrl,
    int? replyToId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
    String? replyToSenderName,
    bool? isForwarded = false,
    List<Map<String, dynamic>>? attachments,
    String? receivedAt,
    String? urgency,
    String? sentiment,
    String? originalSender,
    String? deliveryStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMessageLocally, [], {
              #senderContact: senderContact,
              #body: body,
              #channel: channel,
              #mediaUrl: mediaUrl,
              #replyToId: replyToId,
              #replyToPlatformId: replyToPlatformId,
              #replyToBodyPreview: replyToBodyPreview,
              #replyToSenderName: replyToSenderName,
              #isForwarded: isForwarded,
              #attachments: attachments,
              #receivedAt: receivedAt,
              #urgency: urgency,
              #sentiment: sentiment,
              #originalSender: originalSender,
              #deliveryStatus: deliveryStatus,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getChatHistory(
    String? senderContact, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getChatHistory,
              [senderContact],
              {#limit: limit},
            ),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>?> getMessageWithAttachments(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageWithAttachments, [localId]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getUnsyncedOutgoingMessages(
    String? senderContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUnsyncedOutgoingMessages, [senderContact]),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> deleteOptimisticMessage(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOptimisticMessage, [localId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAsSynced(
    int? localId,
    int? remoteId, {
    String? platformMessageId,
    String? channelMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markAsSynced,
              [localId, remoteId],
              {
                #platformMessageId: platformMessageId,
                #channelMessageId: channelMessageId,
              },
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> incrementRetryCount(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetryCount, [localId]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<bool> hasExceededMaxRetries(int? localId) =>
      (super.noSuchMethod(
            Invocation.method(#hasExceededMaxRetries, [localId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getRetryableMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getRetryableMessages, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> updateMessageStatus(
    int? remoteId,
    String? status, {
    String? editedBody,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateMessageStatus,
              [remoteId, status],
              {#editedBody: editedBody},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearChatHistory(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#clearChatHistory, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateMessageEditLocally(
    int? remoteId,
    String? newBody,
    String? editedAt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageEditLocally, [
              remoteId,
              newBody,
              editedAt,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateMessageSyncStatus(int? remoteId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageSyncStatus, [remoteId, status]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> persistRemoteMessage(Map<String, dynamic>? msg) =>
      (super.noSuchMethod(
            Invocation.method(#persistRemoteMessage, [msg]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<int> insertOutboxMessage({
    required String? channel,
    required String? body,
    String? recipientId,
    String? recipientContact,
    String? subject,
    int? inboxMessageId,
    int? replyToId,
    String? replyToPlatformId,
    String? replyToBodyPreview,
    String? replyToSenderName,
    List<Map<String, dynamic>>? attachments,
    bool? isForwarded = false,
    String? status = 'pending',
    String? deliveryStatus,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertOutboxMessage, [], {
              #channel: channel,
              #body: body,
              #recipientId: recipientId,
              #recipientContact: recipientContact,
              #subject: subject,
              #inboxMessageId: inboxMessageId,
              #replyToId: replyToId,
              #replyToPlatformId: replyToPlatformId,
              #replyToBodyPreview: replyToBodyPreview,
              #replyToSenderName: replyToSenderName,
              #attachments: attachments,
              #isForwarded: isForwarded,
              #status: status,
              #deliveryStatus: deliveryStatus,
            }),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getPendingOutboxMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOutboxMessages, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> markOutboxAsSynced(
    int? localId,
    int? remoteId, {
    String? platformMessageId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #markOutboxAsSynced,
              [localId, remoteId],
              {#platformMessageId: platformMessageId},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateOutboxStatus(
    int? remoteId,
    String? status, {
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateOutboxStatus,
              [remoteId, status],
              {#errorMessage: errorMessage},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteOutboxMessage(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteOutboxMessage, [remoteId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> cacheConversations(
    List<Map<String, dynamic>>? conversations,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheConversations, [conversations]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getConversations({
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<Map<String, dynamic>?> getConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#getConversation, [senderContact]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<void> updateConversationUnreadCount(
    String? senderContact,
    int? unreadCount,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationUnreadCount, [
              senderContact,
              unreadCount,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateConversationOnlineStatus(
    String? senderContact,
    bool? isOnline,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationOnlineStatus, [
              senderContact,
              isOnline,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markConversationAsRead(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationAsRead, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteConversation(String? senderContact) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [senderContact]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearConversations() =>
      (super.noSuchMethod(
            Invocation.method(#clearConversations, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> hasPendingOperation(int? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#hasPendingOperation, [remoteId]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> updateConversationContact(
    String? oldContact,
    String? newContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversationContact, [
              oldContact,
              newContact,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateMessageSenderContact(
    String? oldContact,
    String? newContact,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMessageSenderContact, [
              oldContact,
              newContact,
            ]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secureStorage(_i17.FlutterSecureStorage? storage) => super.noSuchMethod(
    Invocation.setter(#secureStorage, storage),
    returnValueForMissingStub: null,
  );

  @override
  void setTemporaryOverride(String? key) => super.noSuchMethod(
    Invocation.method(#setTemporaryOverride, [key]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<String?> getLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseKey, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<int?> getLicenseId([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseId, [overrideKey]),
            returnValue: _i7.Future<int?>.value(),
          )
          as _i7.Future<int?>);

  @override
  _i7.Future<void> setLicenseInfo({
    required String? key,
    int? id,
    String? accessToken,
    String? refreshToken,
    bool? updateActivePointer = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setLicenseInfo, [], {
              #key: key,
              #id: id,
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #updateActivePointer: updateActivePointer,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> clearLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#clearLicenseKey, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<String> getAccountCacheHash() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountCacheHash, []),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#getAccountCacheHash, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String?> getAccessToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [overrideKey]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, [overrideKey]),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<_i6.Response> getRaw(
    String? url, {
    bool? requiresAuth = false,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRaw,
              [url],
              {
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_7(
                this,
                Invocation.method(
                  #getRaw,
                  [url],
                  {
                    #requiresAuth: requiresAuth,
                    #overrideLicenseKey: overrideLicenseKey,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<Map<String, dynamic>> uploadMultipleFiles(
    String? endpoint, {
    required List<MapEntry<String, String>>? files,
    Map<String, String>? fields,
    String? method = 'POST',
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
    int? retryCount = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMultipleFiles,
              [endpoint],
              {
                #files: files,
                #fields: fields,
                #method: method,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
                #retryCount: retryCount,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<Map<String, dynamic>> uploadFile(
    String? endpoint, {
    required String? filePath,
    required String? fieldName,
    Map<String, String>? fields,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [endpoint],
              {
                #filePath: filePath,
                #fieldName: fieldName,
                #fields: fields,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  void scheduleProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#scheduleProactiveRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#cancelProactiveRefresh, []),
    returnValueForMissingStub: null,
  );
}
