// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/features/tasks/ui/screens/task_edit_screen_offline_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i9;

import 'package:almudeer_mobile_app/data/models/user_info.dart' as _i11;
import 'package:almudeer_mobile_app/features/tasks/models/task_comment_model.dart'
    as _i8;
import 'package:almudeer_mobile_app/features/tasks/models/task_model.dart'
    as _i5;
import 'package:almudeer_mobile_app/features/tasks/providers/task_provider.dart'
    as _i4;
import 'package:almudeer_mobile_app/features/tasks/repositories/task_repository.dart'
    as _i2;
import 'package:almudeer_mobile_app/features/tasks/services/sync_service.dart'
    as _i3;
import 'package:almudeer_mobile_app/presentation/providers/auth_provider.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTaskRepository_0 extends _i1.SmartFake
    implements _i2.TaskRepository {
  _FakeTaskRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTaskSyncService_1 extends _i1.SmartFake
    implements _i3.TaskSyncService {
  _FakeTaskSyncService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TaskProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskProvider extends _i1.Mock implements _i4.TaskProvider {
  MockTaskProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasError =>
      (super.noSuchMethod(Invocation.getter(#hasError), returnValue: false)
          as bool);

  @override
  bool get hasSyncFailure =>
      (super.noSuchMethod(
            Invocation.getter(#hasSyncFailure),
            returnValue: false,
          )
          as bool);

  @override
  bool get canRetry =>
      (super.noSuchMethod(Invocation.getter(#canRetry), returnValue: false)
          as bool);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  List<_i5.TaskModel> get tasks =>
      (super.noSuchMethod(
            Invocation.getter(#tasks),
            returnValue: <_i5.TaskModel>[],
          )
          as List<_i5.TaskModel>);

  @override
  List<Map<String, dynamic>> get collaborators =>
      (super.noSuchMethod(
            Invocation.getter(#collaborators),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  _i4.TaskFilter get filter =>
      (super.noSuchMethod(
            Invocation.getter(#filter),
            returnValue: _i4.TaskFilter.all,
          )
          as _i4.TaskFilter);

  @override
  _i2.TaskRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTaskRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TaskRepository);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<_i5.TaskModel> get filteredTasks =>
      (super.noSuchMethod(
            Invocation.getter(#filteredTasks),
            returnValue: <_i5.TaskModel>[],
          )
          as List<_i5.TaskModel>);

  @override
  List<_i5.TaskModel> get todayTasks =>
      (super.noSuchMethod(
            Invocation.getter(#todayTasks),
            returnValue: <_i5.TaskModel>[],
          )
          as List<_i5.TaskModel>);

  @override
  int get activeTaskCount =>
      (super.noSuchMethod(Invocation.getter(#activeTaskCount), returnValue: 0)
          as int);

  @override
  int get completedTaskCount =>
      (super.noSuchMethod(
            Invocation.getter(#completedTaskCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get isSelectionMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSelectionMode),
            returnValue: false,
          )
          as bool);

  @override
  Set<String> get selectedIds =>
      (super.noSuchMethod(
            Invocation.getter(#selectedIds),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  int get selectedCount =>
      (super.noSuchMethod(Invocation.getter(#selectedCount), returnValue: 0)
          as int);

  @override
  List<_i5.TaskModel> get searchResults =>
      (super.noSuchMethod(
            Invocation.getter(#searchResults),
            returnValue: <_i5.TaskModel>[],
          )
          as List<_i5.TaskModel>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> retryLastOperation() =>
      (super.noSuchMethod(
            Invocation.method(#retryLastOperation, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  Map<String, String> getTypingUsers(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getTypingUsers, [taskId]),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  void clearTypingIndicator(String? taskId) => super.noSuchMethod(
    Invocation.method(#clearTypingIndicator, [taskId]),
    returnValueForMissingStub: null,
  );

  @override
  void setFilter(_i4.TaskFilter? filter) => super.noSuchMethod(
    Invocation.method(#setFilter, [filter]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSelection(String? id) => super.noSuchMethod(
    Invocation.method(#toggleSelection, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i5.TaskModel>> bulkDelete() =>
      (super.noSuchMethod(
            Invocation.method(#bulkDelete, []),
            returnValue: _i7.Future<List<_i5.TaskModel>>.value(
              <_i5.TaskModel>[],
            ),
          )
          as _i7.Future<List<_i5.TaskModel>>);

  @override
  _i7.Future<void> undoBulkDelete(List<_i5.TaskModel>? tasks) =>
      (super.noSuchMethod(
            Invocation.method(#undoBulkDelete, [tasks]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> loadTasks({bool? triggerSync = true}) =>
      (super.noSuchMethod(
            Invocation.method(#loadTasks, [], {#triggerSync: triggerSync}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loadMoreTasks() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreTasks, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loadCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#loadCurrentUser, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> loadCollaborators() =>
      (super.noSuchMethod(
            Invocation.method(#loadCollaborators, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> addTask({
    required String? title,
    String? description,
    DateTime? dueDate,
    bool? alarmEnabled = false,
    DateTime? alarmTime,
    String? recurrence,
    List<_i5.SubTaskModel>? subTasks = const [],
    String? category,
    String? assignedTo,
    List<Map<String, dynamic>>? attachments = const [],
    String? visibility = 'shared',
    _i5.TaskPriority? priority = _i5.TaskPriority.medium,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addTask, [], {
              #title: title,
              #description: description,
              #dueDate: dueDate,
              #alarmEnabled: alarmEnabled,
              #alarmTime: alarmTime,
              #recurrence: recurrence,
              #subTasks: subTasks,
              #category: category,
              #assignedTo: assignedTo,
              #attachments: attachments,
              #visibility: visibility,
              #priority: priority,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> toggleTaskStatus(_i5.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTaskStatus, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.TaskModel?> deleteTask(String? id, {bool? showUndo = false}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id], {#showUndo: showUndo}),
            returnValue: _i7.Future<_i5.TaskModel?>.value(),
          )
          as _i7.Future<_i5.TaskModel?>);

  @override
  _i7.Future<_i5.TaskModel?> deleteTaskWithConfirmation(
    String? id, {
    bool? showUndo = false,
    dynamic context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteTaskWithConfirmation,
              [id],
              {#showUndo: showUndo, #context: context},
            ),
            returnValue: _i7.Future<_i5.TaskModel?>.value(),
          )
          as _i7.Future<_i5.TaskModel?>);

  @override
  _i7.Future<void> undoDeleteTask(_i5.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#undoDeleteTask, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateTask(_i5.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> shareTask({
    required String? taskId,
    required String? sharedWithUserId,
    required String? permission,
    int? expiresInDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareTask, [], {
              #taskId: taskId,
              #sharedWithUserId: sharedWithUserId,
              #permission: permission,
              #expiresInDays: expiresInDays,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> assignTask(String? taskId, String? username) =>
      (super.noSuchMethod(
            Invocation.method(#assignTask, [taskId, username]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> reorderTasks(int? oldIndex, int? newIndex) =>
      (super.noSuchMethod(
            Invocation.method(#reorderTasks, [oldIndex, newIndex]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i8.TaskCommentModel>> getComments(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [taskId]),
            returnValue: _i7.Future<List<_i8.TaskCommentModel>>.value(
              <_i8.TaskCommentModel>[],
            ),
          )
          as _i7.Future<List<_i8.TaskCommentModel>>);

  @override
  _i7.Future<bool> addComment(
    String? taskId,
    String? content, {
    List<String>? attachmentPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [taskId, content],
              {#attachmentPaths: attachmentPaths},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  void setTypingStatus(String? taskId, bool? isTyping) => super.noSuchMethod(
    Invocation.method(#setTypingStatus, [taskId, isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i2.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<void> get syncStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStream),
            returnValue: _i7.Stream<void>.empty(),
          )
          as _i7.Stream<void>);

  @override
  _i7.Stream<Map<String, dynamic>> get typingStream =>
      (super.noSuchMethod(
            Invocation.getter(#typingStream),
            returnValue: _i7.Stream<Map<String, dynamic>>.empty(),
          )
          as _i7.Stream<Map<String, dynamic>>);

  @override
  _i3.TaskSyncService get syncService =>
      (super.noSuchMethod(
            Invocation.getter(#syncService),
            returnValue: _FakeTaskSyncService_1(
              this,
              Invocation.getter(#syncService),
            ),
          )
          as _i3.TaskSyncService);

  @override
  bool get isWebSocketConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isWebSocketConnected),
            returnValue: false,
          )
          as bool);

  @override
  int get wsDisconnectCount =>
      (super.noSuchMethod(Invocation.getter(#wsDisconnectCount), returnValue: 0)
          as int);

  @override
  int get wsReconnectAttempts =>
      (super.noSuchMethod(
            Invocation.getter(#wsReconnectAttempts),
            returnValue: 0,
          )
          as int);

  @override
  _i7.Stream<Map<String, dynamic>> get wsStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#wsStatusStream),
            returnValue: _i7.Stream<Map<String, dynamic>>.empty(),
          )
          as _i7.Stream<Map<String, dynamic>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearCommentCache() => super.noSuchMethod(
    Invocation.method(#clearCommentCache, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i5.TaskModel>> getTasks({
    bool? triggerSync = true,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTasks, [], {
              #triggerSync: triggerSync,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i7.Future<List<_i5.TaskModel>>.value(
              <_i5.TaskModel>[],
            ),
          )
          as _i7.Future<List<_i5.TaskModel>>);

  @override
  _i7.Future<List<_i5.TaskModel>> getSharedTasks({String? permission}) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedTasks, [], {#permission: permission}),
            returnValue: _i7.Future<List<_i5.TaskModel>>.value(
              <_i5.TaskModel>[],
            ),
          )
          as _i7.Future<List<_i5.TaskModel>>);

  @override
  _i7.Future<void> insertTask(_i5.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#insertTask, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateTask(_i5.TaskModel? task) =>
      (super.noSuchMethod(
            Invocation.method(#updateTask, [task]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> shareTask({
    required String? taskId,
    required String? sharedWithUserId,
    required String? permission,
    int? expiresInDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareTask, [], {
              #taskId: taskId,
              #sharedWithUserId: sharedWithUserId,
              #permission: permission,
              #expiresInDays: expiresInDays,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteTask(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTask, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getCollaborators() =>
      (super.noSuchMethod(
            Invocation.method(#getCollaborators, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<List<_i8.TaskCommentModel>> getComments(String? taskId) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [taskId]),
            returnValue: _i7.Future<List<_i8.TaskCommentModel>>.value(
              <_i8.TaskCommentModel>[],
            ),
          )
          as _i7.Future<List<_i8.TaskCommentModel>>);

  @override
  _i7.Future<bool> addComment(
    String? taskId,
    String? content, {
    List<String>? attachmentPaths,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addComment,
              [taskId, content],
              {#attachmentPaths: attachmentPaths},
            ),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<Map<String, dynamic>>> fetchPendingAlarms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPendingAlarms, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<void> syncAlarmsWithBackend() =>
      (super.noSuchMethod(
            Invocation.method(#syncAlarmsWithBackend, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> acknowledgeAlarmOnBackend({
    required int? alarmId,
    String? deviceId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeAlarmOnBackend, [], {
              #alarmId: alarmId,
              #deviceId: deviceId,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<Map<String, dynamic>?> snoozeAlarmOnBackend({
    required String? taskId,
    int? alarmId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#snoozeAlarmOnBackend, [], {
              #taskId: taskId,
              #alarmId: alarmId,
            }),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i10.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get accountKey =>
      (super.noSuchMethod(Invocation.getter(#accountKey), returnValue: 0)
          as int);

  @override
  _i10.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i10.AuthState.initial,
          )
          as _i10.AuthState);

  @override
  List<_i11.UserInfo> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i11.UserInfo>[],
          )
          as List<_i11.UserInfo>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isRateLimited =>
      (super.noSuchMethod(Invocation.getter(#isRateLimited), returnValue: false)
          as bool);

  @override
  int get remainingLockoutMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#remainingLockoutMinutes),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAccountSwitchCallback(_i9.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#setAccountSwitchCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  bool validateLicenseFormat(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#validateLicenseFormat, [key]),
            returnValue: false,
          )
          as bool);

  @override
  String getLicenseFormatErrorMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseFormatErrorMessage, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getLicenseFormatErrorMessage, []),
            ),
          )
          as String);

  @override
  _i7.Future<bool> login(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#login, [licenseKey]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> addAccount(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [licenseKey]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> switchAccount(_i11.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeAccount(_i11.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [user]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> logout({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#reason: reason}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> refreshUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserInfo, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
