// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/presentation/screens/customers/customer_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:almudeer_mobile_app/data/models/conversation.dart' as _i12;
import 'package:almudeer_mobile_app/data/models/customer.dart' as _i3;
import 'package:almudeer_mobile_app/data/models/inbox_message.dart' as _i10;
import 'package:almudeer_mobile_app/data/models/user_info.dart' as _i8;
import 'package:almudeer_mobile_app/presentation/providers/auth_provider.dart'
    as _i7;
import 'package:almudeer_mobile_app/presentation/providers/conversation_detail_provider.dart'
    as _i9;
import 'package:almudeer_mobile_app/presentation/providers/customers_provider.dart'
    as _i2;
import 'package:almudeer_mobile_app/presentation/providers/inbox_provider.dart'
    as _i13;
import 'package:flutter/material.dart' as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CustomersProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomersProvider extends _i1.Mock implements _i2.CustomersProvider {
  MockCustomersProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Customer> get customers =>
      (super.noSuchMethod(
            Invocation.getter(#customers),
            returnValue: <_i3.Customer>[],
          )
          as List<_i3.Customer>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  bool get hasNextPage =>
      (super.noSuchMethod(Invocation.getter(#hasNextPage), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<_i3.Customer> get filteredCustomers =>
      (super.noSuchMethod(
            Invocation.getter(#filteredCustomers),
            returnValue: <_i3.Customer>[],
          )
          as List<_i3.Customer>);

  @override
  bool get isSelectionMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSelectionMode),
            returnValue: false,
          )
          as bool);

  @override
  Set<int> get selectedIds =>
      (super.noSuchMethod(Invocation.getter(#selectedIds), returnValue: <int>{})
          as Set<int>);

  @override
  int get selectedCount =>
      (super.noSuchMethod(Invocation.getter(#selectedCount), returnValue: 0)
          as int);

  @override
  bool get isCheckingUsername =>
      (super.noSuchMethod(
            Invocation.getter(#isCheckingUsername),
            returnValue: false,
          )
          as bool);

  @override
  bool get usernameNotFound =>
      (super.noSuchMethod(
            Invocation.getter(#usernameNotFound),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void toggleSelectionMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleSelectionMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleSelection(int? id) => super.noSuchMethod(
    Invocation.method(#toggleSelection, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> bulkDelete() =>
      (super.noSuchMethod(
            Invocation.method(#bulkDelete, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadCustomers({
    bool? refresh = false,
    bool? triggerSync = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadCustomers, [], {
              #refresh: refresh,
              #triggerSync: triggerSync,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMore() =>
      (super.noSuchMethod(
            Invocation.method(#loadMore, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void lookupUsername(String? username) => super.noSuchMethod(
    Invocation.method(#lookupUsername, [username]),
    returnValueForMissingStub: null,
  );

  @override
  void clearUsernameLookup() => super.noSuchMethod(
    Invocation.method(#clearUsernameLookup, []),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<Map<String, dynamic>> addCustomer(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomer, [data]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  void updateCustomerInList(Map<String, dynamic>? updatedData) =>
      super.noSuchMethod(
        Invocation.method(#updateCustomerInList, [updatedData]),
        returnValueForMissingStub: null,
      );

  @override
  void removeCustomerFromList(dynamic id) => super.noSuchMethod(
    Invocation.method(#removeCustomerFromList, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i3.Customer?> findCustomer({String? phone, String? username}) =>
      (super.noSuchMethod(
            Invocation.method(#findCustomer, [], {
              #phone: phone,
              #username: username,
            }),
            returnValue: _i5.Future<_i3.Customer?>.value(),
          )
          as _i5.Future<_i3.Customer?>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i7.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get accountKey =>
      (super.noSuchMethod(Invocation.getter(#accountKey), returnValue: 0)
          as int);

  @override
  _i7.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i7.AuthState.initial,
          )
          as _i7.AuthState);

  @override
  List<_i8.UserInfo> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i8.UserInfo>[],
          )
          as List<_i8.UserInfo>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isRateLimited =>
      (super.noSuchMethod(Invocation.getter(#isRateLimited), returnValue: false)
          as bool);

  @override
  int get remainingLockoutMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#remainingLockoutMinutes),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAccountSwitchCallback(_i6.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#setAccountSwitchCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool validateLicenseFormat(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#validateLicenseFormat, [key]),
            returnValue: false,
          )
          as bool);

  @override
  String getLicenseFormatErrorMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseFormatErrorMessage, []),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getLicenseFormatErrorMessage, []),
            ),
          )
          as String);

  @override
  _i5.Future<bool> login(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#login, [licenseKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addAccount(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [licenseKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> switchAccount(_i8.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeAccount(_i8.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#reason: reason}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserInfo, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ConversationDetailProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockConversationDetailProvider extends _i1.Mock
    implements _i9.ConversationDetailProvider {
  MockConversationDetailProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ConversationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i9.ConversationState.initial,
          )
          as _i9.ConversationState);

  @override
  List<_i10.InboxMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i10.InboxMessage>[],
          )
          as List<_i10.InboxMessage>);

  @override
  bool get hasMore =>
      (super.noSuchMethod(Invocation.getter(#hasMore), returnValue: false)
          as bool);

  @override
  bool get isPeerTyping =>
      (super.noSuchMethod(Invocation.getter(#isPeerTyping), returnValue: false)
          as bool);

  @override
  bool get isPeerRecording =>
      (super.noSuchMethod(
            Invocation.getter(#isPeerRecording),
            returnValue: false,
          )
          as bool);

  @override
  bool get isPeerOnline =>
      (super.noSuchMethod(Invocation.getter(#isPeerOnline), returnValue: false)
          as bool);

  @override
  bool get isLocalUserOnline =>
      (super.noSuchMethod(
            Invocation.getter(#isLocalUserOnline),
            returnValue: false,
          )
          as bool);

  @override
  bool get isEditing =>
      (super.noSuchMethod(Invocation.getter(#isEditing), returnValue: false)
          as bool);

  @override
  bool get isSearching =>
      (super.noSuchMethod(Invocation.getter(#isSearching), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  List<int> get searchResultIds =>
      (super.noSuchMethod(
            Invocation.getter(#searchResultIds),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  int get currentSearchIndex =>
      (super.noSuchMethod(
            Invocation.getter(#currentSearchIndex),
            returnValue: 0,
          )
          as int);

  @override
  int get totalSearchResults =>
      (super.noSuchMethod(
            Invocation.getter(#totalSearchResults),
            returnValue: 0,
          )
          as int);

  @override
  bool get isSelectionMode =>
      (super.noSuchMethod(
            Invocation.getter(#isSelectionMode),
            returnValue: false,
          )
          as bool);

  @override
  Set<int> get selectedMessageIds =>
      (super.noSuchMethod(
            Invocation.getter(#selectedMessageIds),
            returnValue: <int>{},
          )
          as Set<int>);

  @override
  int get selectedCount =>
      (super.noSuchMethod(Invocation.getter(#selectedCount), returnValue: 0)
          as int);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isLoadingMore =>
      (super.noSuchMethod(Invocation.getter(#isLoadingMore), returnValue: false)
          as bool);

  @override
  List<Map<String, dynamic>> get whatsappTemplates =>
      (super.noSuchMethod(
            Invocation.getter(#whatsappTemplates),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  set onError(_i11.ValueChanged<String>? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool isMessageSelected(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isMessageSelected, [id]),
            returnValue: false,
          )
          as bool);

  @override
  String getDraft(String? contact) =>
      (super.noSuchMethod(
            Invocation.method(#getDraft, [contact]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#getDraft, [contact]),
            ),
          )
          as String);

  @override
  _i5.Future<void> loadConversation(
    String? senderContact, {
    String? senderName,
    String? channel,
    String? lastSeenAt,
    bool? isOnline = false,
    bool? fresh = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #loadConversation,
              [senderContact],
              {
                #senderName: senderName,
                #channel: channel,
                #lastSeenAt: lastSeenAt,
                #isOnline: isOnline,
                #fresh: fresh,
              },
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> loadMoreMessages() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreMessages, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addOptimisticMessage(_i10.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#addOptimisticMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void setReplyMessage(_i10.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#setReplyMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelReply() => super.noSuchMethod(
    Invocation.method(#cancelReply, []),
    returnValueForMissingStub: null,
  );

  @override
  void markMessageFailed(int? tempId) => super.noSuchMethod(
    Invocation.method(#markMessageFailed, [tempId]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageUploadProgress(
    int? messageId,
    double? progress,
    int? uploadedBytes,
    int? totalBytes,
  ) => super.noSuchMethod(
    Invocation.method(#updateMessageUploadProgress, [
      messageId,
      progress,
      uploadedBytes,
      totalBytes,
    ]),
    returnValueForMissingStub: null,
  );

  @override
  void updateMessageAttachments(
    int? messageId,
    List<Map<String, dynamic>>? attachments,
  ) => super.noSuchMethod(
    Invocation.method(#updateMessageAttachments, [messageId, attachments]),
    returnValueForMissingStub: null,
  );

  @override
  void confirmMessageSent(
    int? tempId,
    int? realId,
    String? status, {
    int? outboxId,
  }) => super.noSuchMethod(
    Invocation.method(
      #confirmMessageSent,
      [tempId, realId, status],
      {#outboxId: outboxId},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> editMessage(int? messageId, String? newBody) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [messageId, newBody]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> deleteMessage(int? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> clearActiveChatMessages() =>
      (super.noSuchMethod(
            Invocation.method(#clearActiveChatMessages, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> saveDraft(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#saveDraft, [text]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearDraft(String? contact) => super.noSuchMethod(
    Invocation.method(#clearDraft, [contact]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> fetchWhatsAppTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#fetchWhatsAppTemplates, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void toggleSelectionMode(bool? enabled) => super.noSuchMethod(
    Invocation.method(#toggleSelectionMode, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleMessageSelection(int? id) => super.noSuchMethod(
    Invocation.method(#toggleMessageSelection, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void selectAll() => super.noSuchMethod(
    Invocation.method(#selectAll, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSelection() => super.noSuchMethod(
    Invocation.method(#clearSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  void exitSelectionMode() => super.noSuchMethod(
    Invocation.method(#exitSelectionMode, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectAllMessages() => super.noSuchMethod(
    Invocation.method(#selectAllMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i10.InboxMessage> getSelectedMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getSelectedMessages, []),
            returnValue: <_i10.InboxMessage>[],
          )
          as List<_i10.InboxMessage>);

  @override
  void copySelectedMessages() => super.noSuchMethod(
    Invocation.method(#copySelectedMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> forwardSelectedMessages() =>
      (super.noSuchMethod(
            Invocation.method(#forwardSelectedMessages, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> bulkDeleteMessages() =>
      (super.noSuchMethod(
            Invocation.method(#bulkDeleteMessages, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool undoLastBulkDelete() =>
      (super.noSuchMethod(
            Invocation.method(#undoLastBulkDelete, []),
            returnValue: false,
          )
          as bool);

  @override
  void clearUndoStack() => super.noSuchMethod(
    Invocation.method(#clearUndoStack, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> shareMessages(
    List<int>? messageIds,
    _i12.Conversation? targetConversation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#shareMessages, [messageIds, targetConversation]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void startEditingMessage(_i10.InboxMessage? message) => super.noSuchMethod(
    Invocation.method(#startEditingMessage, [message]),
    returnValueForMissingStub: null,
  );

  @override
  void cancelEditing() => super.noSuchMethod(
    Invocation.method(#cancelEditing, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> saveEditedMessage(
    String? newBody,
    _i13.InboxProvider? inboxProvider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveEditedMessage, [newBody, inboxProvider]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearAllCache() => super.noSuchMethod(
    Invocation.method(#clearAllCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void setTypingStatus(bool? isTyping) => super.noSuchMethod(
    Invocation.method(#setTypingStatus, [isTyping]),
    returnValueForMissingStub: null,
  );

  @override
  void setRecordingStatus(bool? isRecording) => super.noSuchMethod(
    Invocation.method(#setRecordingStatus, [isRecording]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void startSearching() => super.noSuchMethod(
    Invocation.method(#startSearching, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopSearching() => super.noSuchMethod(
    Invocation.method(#stopSearching, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> updateSearchQuery(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#updateSearchQuery, [query]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void nextSearchResult() => super.noSuchMethod(
    Invocation.method(#nextSearchResult, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousSearchResult() => super.noSuchMethod(
    Invocation.method(#previousSearchResult, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
