// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/core/services/deep_link_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i4;

import 'package:almudeer_mobile_app/data/models/user_info.dart' as _i3;
import 'package:almudeer_mobile_app/presentation/providers/auth_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get accountKey =>
      (super.noSuchMethod(Invocation.getter(#accountKey), returnValue: 0)
          as int);

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.AuthState.initial,
          )
          as _i2.AuthState);

  @override
  List<_i3.UserInfo> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i3.UserInfo>[],
          )
          as List<_i3.UserInfo>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isRateLimited =>
      (super.noSuchMethod(Invocation.getter(#isRateLimited), returnValue: false)
          as bool);

  @override
  int get remainingLockoutMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#remainingLockoutMinutes),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAccountSwitchCallback(_i4.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#setAccountSwitchCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  bool validateLicenseFormat(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#validateLicenseFormat, [key]),
            returnValue: false,
          )
          as bool);

  @override
  String getLicenseFormatErrorMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseFormatErrorMessage, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#getLicenseFormatErrorMessage, []),
            ),
          )
          as String);

  @override
  _i5.Future<bool> login(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#login, [licenseKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> addAccount(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [licenseKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> switchAccount(_i3.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeAccount(_i3.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> logout({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#reason: reason}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserInfo, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
