// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/core/services/file_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:almudeer_mobile_app/core/services/file_service.dart' as _i3;
import 'package:cross_file/cross_file.dart' as _i2;
import 'package:file_picker/file_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeXFile_0 extends _i1.SmartFake implements _i2.XFile {
  _FakeXFile_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FilePickerWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerWrapper extends _i1.Mock implements _i3.FilePickerWrapper {
  MockFilePickerWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.FilePickerResult?> pickFiles({
    _i5.FileType? type = _i5.FileType.any,
    List<String>? allowedExtensions,
    bool? allowMultiple = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickFiles, [], {
              #type: type,
              #allowedExtensions: allowedExtensions,
              #allowMultiple: allowMultiple,
            }),
            returnValue: _i4.Future<_i5.FilePickerResult?>.value(),
          )
          as _i4.Future<_i5.FilePickerResult?>);
}

/// A class which mocks [FilePickerResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockFilePickerResult extends _i1.Mock implements _i5.FilePickerResult {
  MockFilePickerResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.PlatformFile> get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: <_i5.PlatformFile>[],
          )
          as List<_i5.PlatformFile>);

  @override
  bool get isSinglePick =>
      (super.noSuchMethod(Invocation.getter(#isSinglePick), returnValue: false)
          as bool);

  @override
  int get count =>
      (super.noSuchMethod(Invocation.getter(#count), returnValue: 0) as int);

  @override
  List<String?> get paths =>
      (super.noSuchMethod(Invocation.getter(#paths), returnValue: <String?>[])
          as List<String?>);

  @override
  List<String?> get names =>
      (super.noSuchMethod(Invocation.getter(#names), returnValue: <String?>[])
          as List<String?>);

  @override
  List<_i2.XFile> get xFiles =>
      (super.noSuchMethod(
            Invocation.getter(#xFiles),
            returnValue: <_i2.XFile>[],
          )
          as List<_i2.XFile>);
}

/// A class which mocks [PlatformFile].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformFile extends _i1.Mock implements _i5.PlatformFile {
  MockPlatformFile() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i6.dummyValue<String>(this, Invocation.getter(#name)),
          )
          as String);

  @override
  int get size =>
      (super.noSuchMethod(Invocation.getter(#size), returnValue: 0) as int);

  @override
  _i2.XFile get xFile =>
      (super.noSuchMethod(
            Invocation.getter(#xFile),
            returnValue: _FakeXFile_0(this, Invocation.getter(#xFile)),
          )
          as _i2.XFile);
}
