// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/presentation/library_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:almudeer_mobile_app/core/api/api_client.dart' as _i2;
import 'package:almudeer_mobile_app/core/services/persistent_cache_service.dart'
    as _i9;
import 'package:almudeer_mobile_app/data/models/library_item.dart' as _i3;
import 'package:almudeer_mobile_app/data/repositories/library_repository.dart'
    as _i5;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i7;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLibraryItem_1 extends _i1.SmartFake implements _i3.LibraryItem {
  _FakeLibraryItem_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LibraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLibraryRepository extends _i1.Mock implements _i5.LibraryRepository {
  MockLibraryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i6.Stream<void> get syncStream =>
      (super.noSuchMethod(
            Invocation.getter(#syncStream),
            returnValue: _i6.Stream<void>.empty(),
          )
          as _i6.Stream<void>);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  _i6.Stream<List<_i3.LibraryItem>> getItemsStream({
    int? customerId,
    String? category,
    String? searchQuery,
    int? page = 1,
    int? pageSize = 20,
    bool? skipCacheEmission = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getItemsStream, [], {
              #customerId: customerId,
              #category: category,
              #searchQuery: searchQuery,
              #page: page,
              #pageSize: pageSize,
              #skipCacheEmission: skipCacheEmission,
            }),
            returnValue: _i6.Stream<List<_i3.LibraryItem>>.empty(),
          )
          as _i6.Stream<List<_i3.LibraryItem>>);

  @override
  _i6.Future<int> createNote({
    required String? title,
    required String? content,
    int? customerId,
    int? localId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createNote, [], {
              #title: title,
              #content: content,
              #customerId: customerId,
              #localId: localId,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<_i3.LibraryItem> uploadFile({
    required String? filePath,
    String? title,
    int? customerId,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [], {
              #filePath: filePath,
              #title: title,
              #customerId: customerId,
              #onProgress: onProgress,
            }),
            returnValue: _i6.Future<_i3.LibraryItem>.value(
              _FakeLibraryItem_1(
                this,
                Invocation.method(#uploadFile, [], {
                  #filePath: filePath,
                  #title: title,
                  #customerId: customerId,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.LibraryItem>);

  @override
  _i6.Future<void> updateItem(
    int? itemId, {
    String? title,
    String? content,
    int? customerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItem,
              [itemId],
              {#title: title, #content: content, #customerId: customerId},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteItem(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItem, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> bulkDelete(List<int>? itemIds) =>
      (super.noSuchMethod(
            Invocation.method(#bulkDelete, [itemIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> syncPendingActions() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingActions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void scheduleSync() => super.noSuchMethod(
    Invocation.method(#scheduleSync, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<int> getStorageUsage() =>
      (super.noSuchMethod(
            Invocation.method(#getStorageUsage, []),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<bool> hasEnoughStorage(int? fileSizeBytes) =>
      (super.noSuchMethod(
            Invocation.method(#hasEnoughStorage, [fileSizeBytes]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, int>> getStorageDetails() =>
      (super.noSuchMethod(
            Invocation.method(#getStorageDetails, []),
            returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i6.Future<Map<String, int>>);

  @override
  _i6.Future<Map<String, dynamic>> exportLibraryItems({String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#exportLibraryItems, [], {#category: category}),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<int> importLibraryItems(Map<String, dynamic>? importData) =>
      (super.noSuchMethod(
            Invocation.method(#importLibraryItems, [importData]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<String?> saveExportToFile(
    Map<String, dynamic>? exportData,
    String? filename,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveExportToFile, [exportData, filename]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, dynamic>> shareItem({
    required int? itemId,
    required String? sharedWithUserId,
    String? permission = 'read',
    int? expiresInDays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#shareItem, [], {
              #itemId: itemId,
              #sharedWithUserId: sharedWithUserId,
              #permission: permission,
              #expiresInDays: expiresInDays,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<_i3.LibraryItem>> getSharedWithMe({String? permission}) =>
      (super.noSuchMethod(
            Invocation.method(#getSharedWithMe, [], {#permission: permission}),
            returnValue: _i6.Future<List<_i3.LibraryItem>>.value(
              <_i3.LibraryItem>[],
            ),
          )
          as _i6.Future<List<_i3.LibraryItem>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> listItemShares(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#listItemShares, [itemId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> removeShare(int? shareId) =>
      (super.noSuchMethod(
            Invocation.method(#removeShare, [shareId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateSharePermission({
    required int? shareId,
    required String? permission,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSharePermission, [], {
              #shareId: shareId,
              #permission: permission,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> pairDevice({
    required String? deviceId,
    required String? deviceName,
    String? pairingCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pairDevice, [], {
              #deviceId: deviceId,
              #deviceName: deviceName,
              #pairingCode: pairingCode,
            }),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> listPairedDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listPairedDevices, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> unpairDevice(int? pairingId) =>
      (super.noSuchMethod(
            Invocation.method(#unpairDevice, [pairingId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> recordDeviceConnection(int? pairingId) =>
      (super.noSuchMethod(
            Invocation.method(#recordDeviceConnection, [pairingId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<List<_i3.LibraryItem>> getTrashItems() =>
      (super.noSuchMethod(
            Invocation.method(#getTrashItems, []),
            returnValue: _i6.Future<List<_i3.LibraryItem>>.value(
              <_i3.LibraryItem>[],
            ),
          )
          as _i6.Future<List<_i3.LibraryItem>>);

  @override
  _i6.Future<void> restoreFromTrash(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromTrash, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deletePermanently(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePermanently, [itemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> emptyTrash() =>
      (super.noSuchMethod(
            Invocation.method(#emptyTrash, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getItemVersions(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getItemVersions, [itemId]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> restoreVersion(int? itemId, int? versionId) =>
      (super.noSuchMethod(
            Invocation.method(#restoreVersion, [itemId, versionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set secureStorage(_i7.FlutterSecureStorage? storage) => super.noSuchMethod(
    Invocation.setter(#secureStorage, storage),
    returnValueForMissingStub: null,
  );

  @override
  void setTemporaryOverride(String? key) => super.noSuchMethod(
    Invocation.method(#setTemporaryOverride, [key]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<String?> getLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseKey, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<int?> getLicenseId([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseId, [overrideKey]),
            returnValue: _i6.Future<int?>.value(),
          )
          as _i6.Future<int?>);

  @override
  _i6.Future<void> setLicenseInfo({
    required String? key,
    int? id,
    String? accessToken,
    String? refreshToken,
    bool? updateActivePointer = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setLicenseInfo, [], {
              #key: key,
              #id: id,
              #accessToken: accessToken,
              #refreshToken: refreshToken,
              #updateActivePointer: updateActivePointer,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearLicenseKey() =>
      (super.noSuchMethod(
            Invocation.method(#clearLicenseKey, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<String> getAccountCacheHash() =>
      (super.noSuchMethod(
            Invocation.method(#getAccountCacheHash, []),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#getAccountCacheHash, []),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String?> getAccessToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getAccessToken, [overrideKey]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<String?> getRefreshToken([String? overrideKey]) =>
      (super.noSuchMethod(
            Invocation.method(#getRefreshToken, [overrideKey]),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, dynamic>> get(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> put(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> patch(
    String? endpoint, {
    Map<String, dynamic>? body,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {
                #body: body,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> delete(
    String? endpoint, {
    Map<String, String>? queryParams,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {
                #queryParams: queryParams,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<_i4.Response> getRaw(
    String? url, {
    bool? requiresAuth = false,
    String? overrideLicenseKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getRaw,
              [url],
              {
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
              },
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #getRaw,
                  [url],
                  {
                    #requiresAuth: requiresAuth,
                    #overrideLicenseKey: overrideLicenseKey,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<Map<String, dynamic>> uploadMultipleFiles(
    String? endpoint, {
    required List<MapEntry<String, String>>? files,
    Map<String, String>? fields,
    String? method = 'POST',
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
    int? retryCount = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMultipleFiles,
              [endpoint],
              {
                #files: files,
                #fields: fields,
                #method: method,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
                #retryCount: retryCount,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> uploadFile(
    String? endpoint, {
    required String? filePath,
    required String? fieldName,
    Map<String, String>? fields,
    bool? requiresAuth = true,
    String? overrideLicenseKey,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadFile,
              [endpoint],
              {
                #filePath: filePath,
                #fieldName: fieldName,
                #fields: fields,
                #requiresAuth: requiresAuth,
                #overrideLicenseKey: overrideLicenseKey,
                #onProgress: onProgress,
              },
            ),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  void scheduleProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#scheduleProactiveRefresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void cancelProactiveRefresh() => super.noSuchMethod(
    Invocation.method(#cancelProactiveRefresh, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PersistentCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersistentCacheService extends _i1.Mock
    implements _i9.PersistentCacheService {
  MockPersistentCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> put(
    String? boxName,
    String? key,
    dynamic data, {
    Duration? expiry,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [boxName, key, data], {#expiry: expiry}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<T?> get<T>(String? boxName, String? key, {Duration? expiry}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [boxName, key], {#expiry: expiry}),
            returnValue: _i6.Future<T?>.value(),
          )
          as _i6.Future<T?>);

  @override
  _i6.Future<void> delete(String? boxName, String? key) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [boxName, key]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearBox(String? boxName) =>
      (super.noSuchMethod(
            Invocation.method(#clearBox, [boxName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> deleteByPrefix(String? boxName, String? prefix) =>
      (super.noSuchMethod(
            Invocation.method(#deleteByPrefix, [boxName, prefix]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
