// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/presentation/screens/settings/settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i8;

import 'package:almudeer_mobile_app/data/models/knowledge_document.dart' as _i3;
import 'package:almudeer_mobile_app/data/models/user_info.dart' as _i10;
import 'package:almudeer_mobile_app/data/models/user_preferences.dart' as _i7;
import 'package:almudeer_mobile_app/presentation/providers/auth_provider.dart'
    as _i9;
import 'package:almudeer_mobile_app/presentation/providers/settings_provider.dart'
    as _i2;
import 'package:file_picker/file_picker.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:permission_handler/permission_handler.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SettingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsProvider extends _i1.Mock implements _i2.SettingsProvider {
  MockSettingsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i2.SettingsState.initial,
          )
          as _i2.SettingsState);

  @override
  _i2.SettingsState get integrationsState =>
      (super.noSuchMethod(
            Invocation.getter(#integrationsState),
            returnValue: _i2.SettingsState.initial,
          )
          as _i2.SettingsState);

  @override
  List<_i3.KnowledgeDocument> get knowledgeDocuments =>
      (super.noSuchMethod(
            Invocation.getter(#knowledgeDocuments),
            returnValue: <_i3.KnowledgeDocument>[],
          )
          as List<_i3.KnowledgeDocument>);

  @override
  List<dynamic> get integrations =>
      (super.noSuchMethod(
            Invocation.getter(#integrations),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  bool get isSaving =>
      (super.noSuchMethod(Invocation.getter(#isSaving), returnValue: false)
          as bool);

  @override
  bool get isUploading =>
      (super.noSuchMethod(Invocation.getter(#isUploading), returnValue: false)
          as bool);

  @override
  double get uploadProgress =>
      (super.noSuchMethod(Invocation.getter(#uploadProgress), returnValue: 0.0)
          as double);

  @override
  _i2.KnowledgeLoadState get knowledgeLoadState =>
      (super.noSuchMethod(
            Invocation.getter(#knowledgeLoadState),
            returnValue: _i2.KnowledgeLoadState.initial,
          )
          as _i2.KnowledgeLoadState);

  @override
  _i4.Future<bool> get isExternalStorageGranted =>
      (super.noSuchMethod(
            Invocation.getter(#isExternalStorageGranted),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> get isSystemAlertWindowGranted =>
      (super.noSuchMethod(
            Invocation.getter(#isSystemAlertWindowGranted),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  List<_i5.PlatformFile> get pendingFiles =>
      (super.noSuchMethod(
            Invocation.getter(#pendingFiles),
            returnValue: <_i5.PlatformFile>[],
          )
          as List<_i5.PlatformFile>);

  @override
  List<_i2.FailedFile> get failedFiles =>
      (super.noSuchMethod(
            Invocation.getter(#failedFiles),
            returnValue: <_i2.FailedFile>[],
          )
          as List<_i2.FailedFile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> loadSettings() =>
      (super.noSuchMethod(
            Invocation.method(#loadSettings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> requestNotificationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestNotificationPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i6.PermissionStatus> checkNotificationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkNotificationPermission, []),
            returnValue: _i4.Future<_i6.PermissionStatus>.value(
              _i6.PermissionStatus.denied,
            ),
          )
          as _i4.Future<_i6.PermissionStatus>);

  @override
  _i4.Future<bool> requestManageExternalStorage() =>
      (super.noSuchMethod(
            Invocation.method(#requestManageExternalStorage, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> requestSystemAlertWindow() =>
      (super.noSuchMethod(
            Invocation.method(#requestSystemAlertWindow, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> openUsageAccessSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openUsageAccessSettings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> openNotificationListenerSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openNotificationListenerSettings, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isAndroid13OrHigher() =>
      (super.noSuchMethod(
            Invocation.method(#isAndroid13OrHigher, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> openAppSettingsSystem() =>
      (super.noSuchMethod(
            Invocation.method(#openAppSettingsSystem, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> savePreferences(_i7.UserPreferences? newPrefs) =>
      (super.noSuchMethod(
            Invocation.method(#savePreferences, [newPrefs]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> addKnowledgeDocument(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addKnowledgeDocument, [text]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateKnowledgeDocument(
    _i3.KnowledgeDocument? doc,
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateKnowledgeDocument, [doc, text]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> deleteKnowledgeDocument(_i3.KnowledgeDocument? doc) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKnowledgeDocument, [doc]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> pickKnowledgeFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickKnowledgeFile, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void removePendingFile(_i5.PlatformFile? file) => super.noSuchMethod(
    Invocation.method(#removePendingFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> uploadPendingFiles() =>
      (super.noSuchMethod(
            Invocation.method(#uploadPendingFiles, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> retryFailedFile(_i5.PlatformFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#retryFailedFile, [file]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void removeFailedFile(_i5.PlatformFile? file) => super.noSuchMethod(
    Invocation.method(#removeFailedFile, [file]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<bool> retryAllFailedFiles() =>
      (super.noSuchMethod(
            Invocation.method(#retryAllFailedFiles, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> loadIntegrations() =>
      (super.noSuchMethod(
            Invocation.method(#loadIntegrations, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> updateChannelSettings(
    String? type,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateChannelSettings, [type, data]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> disconnectChannel(String? type) =>
      (super.noSuchMethod(
            Invocation.method(#disconnectChannel, [type]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> saveTelegramConfig(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveTelegramConfig, [token]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> saveWhatsappConfig(String? phoneId, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveWhatsappConfig, [phoneId, token]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> fetchGmailAuthUrl() =>
      (super.noSuchMethod(
            Invocation.method(#fetchGmailAuthUrl, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get accountKey =>
      (super.noSuchMethod(Invocation.getter(#accountKey), returnValue: 0)
          as int);

  @override
  _i9.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i9.AuthState.initial,
          )
          as _i9.AuthState);

  @override
  List<_i10.UserInfo> get accounts =>
      (super.noSuchMethod(
            Invocation.getter(#accounts),
            returnValue: <_i10.UserInfo>[],
          )
          as List<_i10.UserInfo>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isRateLimited =>
      (super.noSuchMethod(Invocation.getter(#isRateLimited), returnValue: false)
          as bool);

  @override
  int get remainingLockoutMinutes =>
      (super.noSuchMethod(
            Invocation.getter(#remainingLockoutMinutes),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setAccountSwitchCallback(_i8.VoidCallback? callback) =>
      super.noSuchMethod(
        Invocation.method(#setAccountSwitchCallback, [callback]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool validateLicenseFormat(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#validateLicenseFormat, [key]),
            returnValue: false,
          )
          as bool);

  @override
  String getLicenseFormatErrorMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getLicenseFormatErrorMessage, []),
            returnValue: _i11.dummyValue<String>(
              this,
              Invocation.method(#getLicenseFormatErrorMessage, []),
            ),
          )
          as String);

  @override
  _i4.Future<bool> login(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#login, [licenseKey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> addAccount(String? licenseKey) =>
      (super.noSuchMethod(
            Invocation.method(#addAccount, [licenseKey]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> switchAccount(_i10.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#switchAccount, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeAccount(_i10.UserInfo? user) =>
      (super.noSuchMethod(
            Invocation.method(#removeAccount, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout({String? reason}) =>
      (super.noSuchMethod(
            Invocation.method(#logout, [], {#reason: reason}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshUserInfo() =>
      (super.noSuchMethod(
            Invocation.method(#refreshUserInfo, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );
}
