// Mocks generated by Mockito 5.4.6 from annotations
// in almudeer_mobile_app/test/presentation/providers/settings_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:almudeer_mobile_app/core/api/api_client.dart' as _i2;
import 'package:almudeer_mobile_app/data/models/knowledge_document.dart' as _i7;
import 'package:almudeer_mobile_app/data/models/user_preferences.dart' as _i3;
import 'package:almudeer_mobile_app/data/repositories/knowledge_repository.dart'
    as _i6;
import 'package:almudeer_mobile_app/data/repositories/settings_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserPreferences_1 extends _i1.SmartFake
    implements _i3.UserPreferences {
  _FakeUserPreferences_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i4.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient =>
      (super.noSuchMethod(
            Invocation.getter(#apiClient),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)),
          )
          as _i2.ApiClient);

  @override
  _i5.Future<void> savePreferencesLocally(_i3.UserPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#savePreferencesLocally, [preferences]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserPreferences?> getLocalPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getLocalPreferences, []),
            returnValue: _i5.Future<_i3.UserPreferences?>.value(),
          )
          as _i5.Future<_i3.UserPreferences?>);

  @override
  _i5.Future<void> updatePreferences(_i3.UserPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferences, [preferences]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.UserPreferences> getPreferences() =>
      (super.noSuchMethod(
            Invocation.method(#getPreferences, []),
            returnValue: _i5.Future<_i3.UserPreferences>.value(
              _FakeUserPreferences_1(
                this,
                Invocation.method(#getPreferences, []),
              ),
            ),
          )
          as _i5.Future<_i3.UserPreferences>);
}

/// A class which mocks [KnowledgeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnowledgeRepository extends _i1.Mock
    implements _i6.KnowledgeRepository {
  MockKnowledgeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i7.KnowledgeDocument>> getKnowledgeDocuments() =>
      (super.noSuchMethod(
            Invocation.method(#getKnowledgeDocuments, []),
            returnValue: _i5.Future<List<_i7.KnowledgeDocument>>.value(
              <_i7.KnowledgeDocument>[],
            ),
          )
          as _i5.Future<List<_i7.KnowledgeDocument>>);

  @override
  _i5.Future<void> addKnowledgeDocument(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addKnowledgeDocument, [text]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> uploadKnowledgeFile(
    String? filePath, {
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadKnowledgeFile,
              [filePath],
              {#onProgress: onProgress},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteKnowledgeDocument(String? documentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteKnowledgeDocument, [documentId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
